// Code generated by ent, DO NOT EDIT.

package pricealert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pricealert type in the database.
	Label = "price_alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTargetPrice holds the string denoting the target_price field in the database.
	FieldTargetPrice = "target_price"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldLastNotifiedAt holds the string denoting the last_notified_at field in the database.
	FieldLastNotifiedAt = "last_notified_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// EdgeListing holds the string denoting the listing edge name in mutations.
	EdgeListing = "listing"
	// Table holds the table name of the pricealert in the database.
	Table = "price_alerts"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "price_alerts"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_price_alerts"
	// ListingTable is the table that holds the listing relation/edge.
	ListingTable = "price_alerts"
	// ListingInverseTable is the table name for the Listing entity.
	// It exists in this package in order to avoid circular dependency with the "listing" package.
	ListingInverseTable = "listings"
	// ListingColumn is the table column denoting the listing relation/edge.
	ListingColumn = "listing_price_alerts"
)

// Columns holds all SQL columns for pricealert fields.
var Columns = []string{
	FieldID,
	FieldTargetPrice,
	FieldIsActive,
	FieldLastNotifiedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "price_alerts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_price_alerts",
	"listing_price_alerts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PriceAlert queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTargetPrice orders the results by the target_price field.
func ByTargetPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetPrice, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByLastNotifiedAt orders the results by the last_notified_at field.
func ByLastNotifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastNotifiedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}

// ByListingField orders the results by listing field.
func ByListingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListingStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}
func newListingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ListingTable, ListingColumn),
	)
}
