// Code generated by ent, DO NOT EDIT.

package pricealert

import (
	"choseclothes/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLTE(FieldID, id))
}

// TargetPrice applies equality check predicate on the "target_price" field. It's identical to TargetPriceEQ.
func TargetPrice(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldTargetPrice, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldIsActive, v))
}

// LastNotifiedAt applies equality check predicate on the "last_notified_at" field. It's identical to LastNotifiedAtEQ.
func LastNotifiedAt(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldLastNotifiedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// TargetPriceEQ applies the EQ predicate on the "target_price" field.
func TargetPriceEQ(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldTargetPrice, v))
}

// TargetPriceNEQ applies the NEQ predicate on the "target_price" field.
func TargetPriceNEQ(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNEQ(FieldTargetPrice, v))
}

// TargetPriceIn applies the In predicate on the "target_price" field.
func TargetPriceIn(vs ...float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIn(FieldTargetPrice, vs...))
}

// TargetPriceNotIn applies the NotIn predicate on the "target_price" field.
func TargetPriceNotIn(vs ...float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotIn(FieldTargetPrice, vs...))
}

// TargetPriceGT applies the GT predicate on the "target_price" field.
func TargetPriceGT(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGT(FieldTargetPrice, v))
}

// TargetPriceGTE applies the GTE predicate on the "target_price" field.
func TargetPriceGTE(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGTE(FieldTargetPrice, v))
}

// TargetPriceLT applies the LT predicate on the "target_price" field.
func TargetPriceLT(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLT(FieldTargetPrice, v))
}

// TargetPriceLTE applies the LTE predicate on the "target_price" field.
func TargetPriceLTE(v float64) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLTE(FieldTargetPrice, v))
}

// TargetPriceIsNil applies the IsNil predicate on the "target_price" field.
func TargetPriceIsNil() predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIsNull(FieldTargetPrice))
}

// TargetPriceNotNil applies the NotNil predicate on the "target_price" field.
func TargetPriceNotNil() predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotNull(FieldTargetPrice))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNEQ(FieldIsActive, v))
}

// LastNotifiedAtEQ applies the EQ predicate on the "last_notified_at" field.
func LastNotifiedAtEQ(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldLastNotifiedAt, v))
}

// LastNotifiedAtNEQ applies the NEQ predicate on the "last_notified_at" field.
func LastNotifiedAtNEQ(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNEQ(FieldLastNotifiedAt, v))
}

// LastNotifiedAtIn applies the In predicate on the "last_notified_at" field.
func LastNotifiedAtIn(vs ...time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIn(FieldLastNotifiedAt, vs...))
}

// LastNotifiedAtNotIn applies the NotIn predicate on the "last_notified_at" field.
func LastNotifiedAtNotIn(vs ...time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotIn(FieldLastNotifiedAt, vs...))
}

// LastNotifiedAtGT applies the GT predicate on the "last_notified_at" field.
func LastNotifiedAtGT(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGT(FieldLastNotifiedAt, v))
}

// LastNotifiedAtGTE applies the GTE predicate on the "last_notified_at" field.
func LastNotifiedAtGTE(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGTE(FieldLastNotifiedAt, v))
}

// LastNotifiedAtLT applies the LT predicate on the "last_notified_at" field.
func LastNotifiedAtLT(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLT(FieldLastNotifiedAt, v))
}

// LastNotifiedAtLTE applies the LTE predicate on the "last_notified_at" field.
func LastNotifiedAtLTE(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLTE(FieldLastNotifiedAt, v))
}

// LastNotifiedAtIsNil applies the IsNil predicate on the "last_notified_at" field.
func LastNotifiedAtIsNil() predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIsNull(FieldLastNotifiedAt))
}

// LastNotifiedAtNotNil applies the NotNil predicate on the "last_notified_at" field.
func LastNotifiedAtNotNil() predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotNull(FieldLastNotifiedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PriceAlert {
	return predicate.PriceAlert(sql.FieldLTE(FieldCreatedAt, v))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.PriceAlert {
	return predicate.PriceAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.PriceAlert {
	return predicate.PriceAlert(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasListing applies the HasEdge predicate on the "listing" edge.
func HasListing() predicate.PriceAlert {
	return predicate.PriceAlert(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ListingTable, ListingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasListingWith applies the HasEdge predicate on the "listing" edge with a given conditions (other predicates).
func HasListingWith(preds ...predicate.Listing) predicate.PriceAlert {
	return predicate.PriceAlert(func(s *sql.Selector) {
		step := newListingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PriceAlert) predicate.PriceAlert {
	return predicate.PriceAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PriceAlert) predicate.PriceAlert {
	return predicate.PriceAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PriceAlert) predicate.PriceAlert {
	return predicate.PriceAlert(sql.NotPredicates(p))
}
