// Code generated by ent, DO NOT EDIT.

package listing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the listing type in the database.
	Label = "listing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldExternalID holds the string denoting the external_id field in the database.
	FieldExternalID = "external_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSellerName holds the string denoting the seller_name field in the database.
	FieldSellerName = "seller_name"
	// FieldSellerRating holds the string denoting the seller_rating field in the database.
	FieldSellerRating = "seller_rating"
	// FieldProductURL holds the string denoting the product_url field in the database.
	FieldProductURL = "product_url"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeSource holds the string denoting the source edge name in mutations.
	EdgeSource = "source"
	// EdgePriceAlerts holds the string denoting the price_alerts edge name in mutations.
	EdgePriceAlerts = "price_alerts"
	// EdgePriceHistory holds the string denoting the price_history edge name in mutations.
	EdgePriceHistory = "price_history"
	// Table holds the table name of the listing in the database.
	Table = "listings"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "listings"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_listings"
	// SourceTable is the table that holds the source relation/edge.
	SourceTable = "listings"
	// SourceInverseTable is the table name for the Source entity.
	// It exists in this package in order to avoid circular dependency with the "source" package.
	SourceInverseTable = "sources"
	// SourceColumn is the table column denoting the source relation/edge.
	SourceColumn = "source_listings"
	// PriceAlertsTable is the table that holds the price_alerts relation/edge.
	PriceAlertsTable = "price_alerts"
	// PriceAlertsInverseTable is the table name for the PriceAlert entity.
	// It exists in this package in order to avoid circular dependency with the "pricealert" package.
	PriceAlertsInverseTable = "price_alerts"
	// PriceAlertsColumn is the table column denoting the price_alerts relation/edge.
	PriceAlertsColumn = "listing_price_alerts"
	// PriceHistoryTable is the table that holds the price_history relation/edge.
	PriceHistoryTable = "price_history"
	// PriceHistoryInverseTable is the table name for the PriceHistory entity.
	// It exists in this package in order to avoid circular dependency with the "pricehistory" package.
	PriceHistoryInverseTable = "price_history"
	// PriceHistoryColumn is the table column denoting the price_history relation/edge.
	PriceHistoryColumn = "listing_price_history"
)

// Columns holds all SQL columns for listing fields.
var Columns = []string{
	FieldID,
	FieldExternalID,
	FieldTitle,
	FieldSellerName,
	FieldSellerRating,
	FieldProductURL,
	FieldCurrency,
	FieldIsActive,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "listings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"product_listings",
	"source_listings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	ExternalIDValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// ProductURLValidator is a validator for the "product_url" field. It is called by the builders before save.
	ProductURLValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Listing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByExternalID orders the results by the external_id field.
func ByExternalID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySellerName orders the results by the seller_name field.
func BySellerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerName, opts...).ToFunc()
}

// BySellerRating orders the results by the seller_rating field.
func BySellerRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellerRating, opts...).ToFunc()
}

// ByProductURL orders the results by the product_url field.
func ByProductURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductURL, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}

// BySourceField orders the results by source field.
func BySourceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSourceStep(), sql.OrderByField(field, opts...))
	}
}

// ByPriceAlertsCount orders the results by price_alerts count.
func ByPriceAlertsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPriceAlertsStep(), opts...)
	}
}

// ByPriceAlerts orders the results by price_alerts terms.
func ByPriceAlerts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPriceAlertsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPriceHistoryCount orders the results by price_history count.
func ByPriceHistoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPriceHistoryStep(), opts...)
	}
}

// ByPriceHistory orders the results by price_history terms.
func ByPriceHistory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPriceHistoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
func newSourceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SourceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
	)
}
func newPriceAlertsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PriceAlertsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PriceAlertsTable, PriceAlertsColumn),
	)
}
func newPriceHistoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PriceHistoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PriceHistoryTable, PriceHistoryColumn),
	)
}
