// Code generated by ent, DO NOT EDIT.

package listing

import (
	"choseclothes/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldID, id))
}

// ExternalID applies equality check predicate on the "external_id" field. It's identical to ExternalIDEQ.
func ExternalID(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldExternalID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTitle, v))
}

// SellerName applies equality check predicate on the "seller_name" field. It's identical to SellerNameEQ.
func SellerName(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldSellerName, v))
}

// SellerRating applies equality check predicate on the "seller_rating" field. It's identical to SellerRatingEQ.
func SellerRating(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldSellerRating, v))
}

// ProductURL applies equality check predicate on the "product_url" field. It's identical to ProductURLEQ.
func ProductURL(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldProductURL, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCurrency, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCreatedAt, v))
}

// ExternalIDEQ applies the EQ predicate on the "external_id" field.
func ExternalIDEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldExternalID, v))
}

// ExternalIDNEQ applies the NEQ predicate on the "external_id" field.
func ExternalIDNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldExternalID, v))
}

// ExternalIDIn applies the In predicate on the "external_id" field.
func ExternalIDIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldExternalID, vs...))
}

// ExternalIDNotIn applies the NotIn predicate on the "external_id" field.
func ExternalIDNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldExternalID, vs...))
}

// ExternalIDGT applies the GT predicate on the "external_id" field.
func ExternalIDGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldExternalID, v))
}

// ExternalIDGTE applies the GTE predicate on the "external_id" field.
func ExternalIDGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldExternalID, v))
}

// ExternalIDLT applies the LT predicate on the "external_id" field.
func ExternalIDLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldExternalID, v))
}

// ExternalIDLTE applies the LTE predicate on the "external_id" field.
func ExternalIDLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldExternalID, v))
}

// ExternalIDContains applies the Contains predicate on the "external_id" field.
func ExternalIDContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldExternalID, v))
}

// ExternalIDHasPrefix applies the HasPrefix predicate on the "external_id" field.
func ExternalIDHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldExternalID, v))
}

// ExternalIDHasSuffix applies the HasSuffix predicate on the "external_id" field.
func ExternalIDHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldExternalID, v))
}

// ExternalIDEqualFold applies the EqualFold predicate on the "external_id" field.
func ExternalIDEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldExternalID, v))
}

// ExternalIDContainsFold applies the ContainsFold predicate on the "external_id" field.
func ExternalIDContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldExternalID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldTitle, v))
}

// SellerNameEQ applies the EQ predicate on the "seller_name" field.
func SellerNameEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldSellerName, v))
}

// SellerNameNEQ applies the NEQ predicate on the "seller_name" field.
func SellerNameNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldSellerName, v))
}

// SellerNameIn applies the In predicate on the "seller_name" field.
func SellerNameIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldSellerName, vs...))
}

// SellerNameNotIn applies the NotIn predicate on the "seller_name" field.
func SellerNameNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldSellerName, vs...))
}

// SellerNameGT applies the GT predicate on the "seller_name" field.
func SellerNameGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldSellerName, v))
}

// SellerNameGTE applies the GTE predicate on the "seller_name" field.
func SellerNameGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldSellerName, v))
}

// SellerNameLT applies the LT predicate on the "seller_name" field.
func SellerNameLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldSellerName, v))
}

// SellerNameLTE applies the LTE predicate on the "seller_name" field.
func SellerNameLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldSellerName, v))
}

// SellerNameContains applies the Contains predicate on the "seller_name" field.
func SellerNameContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldSellerName, v))
}

// SellerNameHasPrefix applies the HasPrefix predicate on the "seller_name" field.
func SellerNameHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldSellerName, v))
}

// SellerNameHasSuffix applies the HasSuffix predicate on the "seller_name" field.
func SellerNameHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldSellerName, v))
}

// SellerNameIsNil applies the IsNil predicate on the "seller_name" field.
func SellerNameIsNil() predicate.Listing {
	return predicate.Listing(sql.FieldIsNull(FieldSellerName))
}

// SellerNameNotNil applies the NotNil predicate on the "seller_name" field.
func SellerNameNotNil() predicate.Listing {
	return predicate.Listing(sql.FieldNotNull(FieldSellerName))
}

// SellerNameEqualFold applies the EqualFold predicate on the "seller_name" field.
func SellerNameEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldSellerName, v))
}

// SellerNameContainsFold applies the ContainsFold predicate on the "seller_name" field.
func SellerNameContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldSellerName, v))
}

// SellerRatingEQ applies the EQ predicate on the "seller_rating" field.
func SellerRatingEQ(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldSellerRating, v))
}

// SellerRatingNEQ applies the NEQ predicate on the "seller_rating" field.
func SellerRatingNEQ(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldSellerRating, v))
}

// SellerRatingIn applies the In predicate on the "seller_rating" field.
func SellerRatingIn(vs ...float64) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldSellerRating, vs...))
}

// SellerRatingNotIn applies the NotIn predicate on the "seller_rating" field.
func SellerRatingNotIn(vs ...float64) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldSellerRating, vs...))
}

// SellerRatingGT applies the GT predicate on the "seller_rating" field.
func SellerRatingGT(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldSellerRating, v))
}

// SellerRatingGTE applies the GTE predicate on the "seller_rating" field.
func SellerRatingGTE(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldSellerRating, v))
}

// SellerRatingLT applies the LT predicate on the "seller_rating" field.
func SellerRatingLT(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldSellerRating, v))
}

// SellerRatingLTE applies the LTE predicate on the "seller_rating" field.
func SellerRatingLTE(v float64) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldSellerRating, v))
}

// SellerRatingIsNil applies the IsNil predicate on the "seller_rating" field.
func SellerRatingIsNil() predicate.Listing {
	return predicate.Listing(sql.FieldIsNull(FieldSellerRating))
}

// SellerRatingNotNil applies the NotNil predicate on the "seller_rating" field.
func SellerRatingNotNil() predicate.Listing {
	return predicate.Listing(sql.FieldNotNull(FieldSellerRating))
}

// ProductURLEQ applies the EQ predicate on the "product_url" field.
func ProductURLEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldProductURL, v))
}

// ProductURLNEQ applies the NEQ predicate on the "product_url" field.
func ProductURLNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldProductURL, v))
}

// ProductURLIn applies the In predicate on the "product_url" field.
func ProductURLIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldProductURL, vs...))
}

// ProductURLNotIn applies the NotIn predicate on the "product_url" field.
func ProductURLNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldProductURL, vs...))
}

// ProductURLGT applies the GT predicate on the "product_url" field.
func ProductURLGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldProductURL, v))
}

// ProductURLGTE applies the GTE predicate on the "product_url" field.
func ProductURLGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldProductURL, v))
}

// ProductURLLT applies the LT predicate on the "product_url" field.
func ProductURLLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldProductURL, v))
}

// ProductURLLTE applies the LTE predicate on the "product_url" field.
func ProductURLLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldProductURL, v))
}

// ProductURLContains applies the Contains predicate on the "product_url" field.
func ProductURLContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldProductURL, v))
}

// ProductURLHasPrefix applies the HasPrefix predicate on the "product_url" field.
func ProductURLHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldProductURL, v))
}

// ProductURLHasSuffix applies the HasSuffix predicate on the "product_url" field.
func ProductURLHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldProductURL, v))
}

// ProductURLEqualFold applies the EqualFold predicate on the "product_url" field.
func ProductURLEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldProductURL, v))
}

// ProductURLContainsFold applies the ContainsFold predicate on the "product_url" field.
func ProductURLContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldProductURL, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Listing {
	return predicate.Listing(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Listing {
	return predicate.Listing(sql.FieldContainsFold(FieldCurrency, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Listing {
	return predicate.Listing(sql.FieldLTE(FieldCreatedAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSource applies the HasEdge predicate on the "source" edge.
func HasSource() predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SourceTable, SourceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSourceWith applies the HasEdge predicate on the "source" edge with a given conditions (other predicates).
func HasSourceWith(preds ...predicate.Source) predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := newSourceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPriceAlerts applies the HasEdge predicate on the "price_alerts" edge.
func HasPriceAlerts() predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PriceAlertsTable, PriceAlertsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPriceAlertsWith applies the HasEdge predicate on the "price_alerts" edge with a given conditions (other predicates).
func HasPriceAlertsWith(preds ...predicate.PriceAlert) predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := newPriceAlertsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPriceHistory applies the HasEdge predicate on the "price_history" edge.
func HasPriceHistory() predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PriceHistoryTable, PriceHistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPriceHistoryWith applies the HasEdge predicate on the "price_history" edge with a given conditions (other predicates).
func HasPriceHistoryWith(preds ...predicate.PriceHistory) predicate.Listing {
	return predicate.Listing(func(s *sql.Selector) {
		step := newPriceHistoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Listing) predicate.Listing {
	return predicate.Listing(sql.NotPredicates(p))
}
