// Code generated by ent, DO NOT EDIT.

package source

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the source type in the database.
	Label = "source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// EdgeListings holds the string denoting the listings edge name in mutations.
	EdgeListings = "listings"
	// Table holds the table name of the source in the database.
	Table = "sources"
	// ListingsTable is the table that holds the listings relation/edge.
	ListingsTable = "listings"
	// ListingsInverseTable is the table name for the Listing entity.
	// It exists in this package in order to avoid circular dependency with the "listing" package.
	ListingsInverseTable = "listings"
	// ListingsColumn is the table column denoting the listings relation/edge.
	ListingsColumn = "source_listings"
)

// Columns holds all SQL columns for source fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the Source queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByListingsCount orders the results by listings count.
func ByListingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newListingsStep(), opts...)
	}
}

// ByListings orders the results by listings terms.
func ByListings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newListingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ListingsTable, ListingsColumn),
	)
}
