// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ChannelsColumns holds the columns for the "channels" table.
	ChannelsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "external_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ChannelsTable holds the schema information for the "channels" table.
	ChannelsTable = &schema.Table{
		Name:       "channels",
		Columns:    ChannelsColumns,
		PrimaryKey: []*schema.Column{ChannelsColumns[0]},
	}
	// ListingsColumns holds the columns for the "listings" table.
	ListingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "external_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "seller_name", Type: field.TypeString, Nullable: true},
		{Name: "seller_rating", Type: field.TypeFloat64, Nullable: true},
		{Name: "product_url", Type: field.TypeString},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "product_listings", Type: field.TypeInt},
		{Name: "source_listings", Type: field.TypeInt},
	}
	// ListingsTable holds the schema information for the "listings" table.
	ListingsTable = &schema.Table{
		Name:       "listings",
		Columns:    ListingsColumns,
		PrimaryKey: []*schema.Column{ListingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "listings_products_listings",
				Columns:    []*schema.Column{ListingsColumns[9]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "listings_sources_listings",
				Columns:    []*schema.Column{ListingsColumns[10]},
				RefColumns: []*schema.Column{SourcesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "listing_external_id_source_listings",
				Unique:  true,
				Columns: []*schema.Column{ListingsColumns[1], ListingsColumns[10]},
			},
		},
	}
	// PriceAlertsColumns holds the columns for the "price_alerts" table.
	PriceAlertsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "target_price", Type: field.TypeFloat64, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_notified_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "channel_price_alerts", Type: field.TypeInt},
		{Name: "listing_price_alerts", Type: field.TypeInt},
	}
	// PriceAlertsTable holds the schema information for the "price_alerts" table.
	PriceAlertsTable = &schema.Table{
		Name:       "price_alerts",
		Columns:    PriceAlertsColumns,
		PrimaryKey: []*schema.Column{PriceAlertsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "price_alerts_channels_price_alerts",
				Columns:    []*schema.Column{PriceAlertsColumns[5]},
				RefColumns: []*schema.Column{ChannelsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "price_alerts_listings_price_alerts",
				Columns:    []*schema.Column{PriceAlertsColumns[6]},
				RefColumns: []*schema.Column{ListingsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PriceHistoryColumns holds the columns for the "price_history" table.
	PriceHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "discount_price", Type: field.TypeFloat64, Nullable: true},
		{Name: "recorded_at", Type: field.TypeTime},
		{Name: "listing_price_history", Type: field.TypeInt},
	}
	// PriceHistoryTable holds the schema information for the "price_history" table.
	PriceHistoryTable = &schema.Table{
		Name:       "price_history",
		Columns:    PriceHistoryColumns,
		PrimaryKey: []*schema.Column{PriceHistoryColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "price_history_listings_price_history",
				Columns:    []*schema.Column{PriceHistoryColumns[4]},
				RefColumns: []*schema.Column{ListingsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pricehistory_recorded_at",
				Unique:  false,
				Columns: []*schema.Column{PriceHistoryColumns[3]},
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// SourcesColumns holds the columns for the "sources" table.
	SourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// SourcesTable holds the schema information for the "sources" table.
	SourcesTable = &schema.Table{
		Name:       "sources",
		Columns:    SourcesColumns,
		PrimaryKey: []*schema.Column{SourcesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "google_id", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "profile_picture", Type: field.TypeString, Nullable: true},
		{Name: "is_subscriber", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ChannelsTable,
		ListingsTable,
		PriceAlertsTable,
		PriceHistoryTable,
		ProductsTable,
		SourcesTable,
		UsersTable,
	}
)

func init() {
	ListingsTable.ForeignKeys[0].RefTable = ProductsTable
	ListingsTable.ForeignKeys[1].RefTable = SourcesTable
	PriceAlertsTable.ForeignKeys[0].RefTable = ChannelsTable
	PriceAlertsTable.ForeignKeys[1].RefTable = ListingsTable
	PriceHistoryTable.ForeignKeys[0].RefTable = ListingsTable
	PriceHistoryTable.Annotation = &entsql.Annotation{
		Table: "price_history",
	}
}
