// Code generated by ent, DO NOT EDIT.

package pricehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pricehistory type in the database.
	Label = "price_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldDiscountPrice holds the string denoting the discount_price field in the database.
	FieldDiscountPrice = "discount_price"
	// FieldRecordedAt holds the string denoting the recorded_at field in the database.
	FieldRecordedAt = "recorded_at"
	// EdgeListing holds the string denoting the listing edge name in mutations.
	EdgeListing = "listing"
	// Table holds the table name of the pricehistory in the database.
	Table = "price_history"
	// ListingTable is the table that holds the listing relation/edge.
	ListingTable = "price_history"
	// ListingInverseTable is the table name for the Listing entity.
	// It exists in this package in order to avoid circular dependency with the "listing" package.
	ListingInverseTable = "listings"
	// ListingColumn is the table column denoting the listing relation/edge.
	ListingColumn = "listing_price_history"
)

// Columns holds all SQL columns for pricehistory fields.
var Columns = []string{
	FieldID,
	FieldPrice,
	FieldDiscountPrice,
	FieldRecordedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "price_history"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"listing_price_history",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRecordedAt holds the default value on creation for the "recorded_at" field.
	DefaultRecordedAt func() time.Time
)

// OrderOption defines the ordering options for the PriceHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByDiscountPrice orders the results by the discount_price field.
func ByDiscountPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscountPrice, opts...).ToFunc()
}

// ByRecordedAt orders the results by the recorded_at field.
func ByRecordedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordedAt, opts...).ToFunc()
}

// ByListingField orders the results by listing field.
func ByListingField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newListingStep(), sql.OrderByField(field, opts...))
	}
}
func newListingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ListingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ListingTable, ListingColumn),
	)
}
