// Code generated by ent, DO NOT EDIT.

package pricehistory

import (
	"choseclothes/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldID, id))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldPrice, v))
}

// DiscountPrice applies equality check predicate on the "discount_price" field. It's identical to DiscountPriceEQ.
func DiscountPrice(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldDiscountPrice, v))
}

// RecordedAt applies equality check predicate on the "recorded_at" field. It's identical to RecordedAtEQ.
func RecordedAt(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldPrice, v))
}

// DiscountPriceEQ applies the EQ predicate on the "discount_price" field.
func DiscountPriceEQ(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldDiscountPrice, v))
}

// DiscountPriceNEQ applies the NEQ predicate on the "discount_price" field.
func DiscountPriceNEQ(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldDiscountPrice, v))
}

// DiscountPriceIn applies the In predicate on the "discount_price" field.
func DiscountPriceIn(vs ...float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldDiscountPrice, vs...))
}

// DiscountPriceNotIn applies the NotIn predicate on the "discount_price" field.
func DiscountPriceNotIn(vs ...float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldDiscountPrice, vs...))
}

// DiscountPriceGT applies the GT predicate on the "discount_price" field.
func DiscountPriceGT(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldDiscountPrice, v))
}

// DiscountPriceGTE applies the GTE predicate on the "discount_price" field.
func DiscountPriceGTE(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldDiscountPrice, v))
}

// DiscountPriceLT applies the LT predicate on the "discount_price" field.
func DiscountPriceLT(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldDiscountPrice, v))
}

// DiscountPriceLTE applies the LTE predicate on the "discount_price" field.
func DiscountPriceLTE(v float64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldDiscountPrice, v))
}

// DiscountPriceIsNil applies the IsNil predicate on the "discount_price" field.
func DiscountPriceIsNil() predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIsNull(FieldDiscountPrice))
}

// DiscountPriceNotNil applies the NotNil predicate on the "discount_price" field.
func DiscountPriceNotNil() predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotNull(FieldDiscountPrice))
}

// RecordedAtEQ applies the EQ predicate on the "recorded_at" field.
func RecordedAtEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldRecordedAt, v))
}

// RecordedAtNEQ applies the NEQ predicate on the "recorded_at" field.
func RecordedAtNEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldRecordedAt, v))
}

// RecordedAtIn applies the In predicate on the "recorded_at" field.
func RecordedAtIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldRecordedAt, vs...))
}

// RecordedAtNotIn applies the NotIn predicate on the "recorded_at" field.
func RecordedAtNotIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldRecordedAt, vs...))
}

// RecordedAtGT applies the GT predicate on the "recorded_at" field.
func RecordedAtGT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldRecordedAt, v))
}

// RecordedAtGTE applies the GTE predicate on the "recorded_at" field.
func RecordedAtGTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldRecordedAt, v))
}

// RecordedAtLT applies the LT predicate on the "recorded_at" field.
func RecordedAtLT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldRecordedAt, v))
}

// RecordedAtLTE applies the LTE predicate on the "recorded_at" field.
func RecordedAtLTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldRecordedAt, v))
}

// HasListing applies the HasEdge predicate on the "listing" edge.
func HasListing() predicate.PriceHistory {
	return predicate.PriceHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ListingTable, ListingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasListingWith applies the HasEdge predicate on the "listing" edge with a given conditions (other predicates).
func HasListingWith(preds ...predicate.Listing) predicate.PriceHistory {
	return predicate.PriceHistory(func(s *sql.Selector) {
		step := newListingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.NotPredicates(p))
}
