// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricealert"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChannelUpdate is the builder for updating Channel entities.
type ChannelUpdate struct {
	config
	hooks    []Hook
	mutation *ChannelMutation
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdate) Where(ps ...predicate.Channel) *ChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *ChannelUpdate) SetType(v string) *ChannelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableType(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ChannelUpdate) SetExternalID(v string) *ChannelUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableExternalID(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdate) SetName(v string) *ChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableName(v *string) *ChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChannelUpdate) ClearName() *ChannelUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ChannelUpdate) SetIsActive(v bool) *ChannelUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableIsActive(v *bool) *ChannelUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChannelUpdate) SetCreatedAt(v time.Time) *ChannelUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChannelUpdate) SetNillableCreatedAt(v *time.Time) *ChannelUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddPriceAlertIDs adds the "price_alerts" edge to the PriceAlert entity by IDs.
func (_u *ChannelUpdate) AddPriceAlertIDs(ids ...int) *ChannelUpdate {
	_u.mutation.AddPriceAlertIDs(ids...)
	return _u
}

// AddPriceAlerts adds the "price_alerts" edges to the PriceAlert entity.
func (_u *ChannelUpdate) AddPriceAlerts(v ...*PriceAlert) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceAlertIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdate) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearPriceAlerts clears all "price_alerts" edges to the PriceAlert entity.
func (_u *ChannelUpdate) ClearPriceAlerts() *ChannelUpdate {
	_u.mutation.ClearPriceAlerts()
	return _u
}

// RemovePriceAlertIDs removes the "price_alerts" edge to PriceAlert entities by IDs.
func (_u *ChannelUpdate) RemovePriceAlertIDs(ids ...int) *ChannelUpdate {
	_u.mutation.RemovePriceAlertIDs(ids...)
	return _u
}

// RemovePriceAlerts removes "price_alerts" edges to PriceAlert entities.
func (_u *ChannelUpdate) RemovePriceAlerts(v ...*PriceAlert) *ChannelUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceAlertIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := channel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Channel.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := channel.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Channel.external_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(channel.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(channel.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(channel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(channel.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceAlertsIDs(); len(nodes) > 0 && !_u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelUpdateOne is the builder for updating a single Channel entity.
type ChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChannelMutation
}

// SetType sets the "type" field.
func (_u *ChannelUpdateOne) SetType(v string) *ChannelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableType(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ChannelUpdateOne) SetExternalID(v string) *ChannelUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableExternalID(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelUpdateOne) SetName(v string) *ChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableName(v *string) *ChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChannelUpdateOne) ClearName() *ChannelUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ChannelUpdateOne) SetIsActive(v bool) *ChannelUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableIsActive(v *bool) *ChannelUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ChannelUpdateOne) SetCreatedAt(v time.Time) *ChannelUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ChannelUpdateOne) SetNillableCreatedAt(v *time.Time) *ChannelUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddPriceAlertIDs adds the "price_alerts" edge to the PriceAlert entity by IDs.
func (_u *ChannelUpdateOne) AddPriceAlertIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.AddPriceAlertIDs(ids...)
	return _u
}

// AddPriceAlerts adds the "price_alerts" edges to the PriceAlert entity.
func (_u *ChannelUpdateOne) AddPriceAlerts(v ...*PriceAlert) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceAlertIDs(ids...)
}

// Mutation returns the ChannelMutation object of the builder.
func (_u *ChannelUpdateOne) Mutation() *ChannelMutation {
	return _u.mutation
}

// ClearPriceAlerts clears all "price_alerts" edges to the PriceAlert entity.
func (_u *ChannelUpdateOne) ClearPriceAlerts() *ChannelUpdateOne {
	_u.mutation.ClearPriceAlerts()
	return _u
}

// RemovePriceAlertIDs removes the "price_alerts" edge to PriceAlert entities by IDs.
func (_u *ChannelUpdateOne) RemovePriceAlertIDs(ids ...int) *ChannelUpdateOne {
	_u.mutation.RemovePriceAlertIDs(ids...)
	return _u
}

// RemovePriceAlerts removes "price_alerts" edges to PriceAlert entities.
func (_u *ChannelUpdateOne) RemovePriceAlerts(v ...*PriceAlert) *ChannelUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceAlertIDs(ids...)
}

// Where appends a list predicates to the ChannelUpdate builder.
func (_u *ChannelUpdateOne) Where(ps ...predicate.Channel) *ChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelUpdateOne) Select(field string, fields ...string) *ChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Channel entity.
func (_u *ChannelUpdateOne) Save(ctx context.Context) (*Channel, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelUpdateOne) SaveX(ctx context.Context) *Channel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := channel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Channel.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := channel.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Channel.external_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ChannelUpdateOne) sqlSave(ctx context.Context) (_node *Channel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channel.Table, channel.Columns, sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Channel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channel.FieldID)
		for _, f := range fields {
			if !channel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(channel.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(channel.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(channel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(channel.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(channel.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceAlertsIDs(); len(nodes) > 0 && !_u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   channel.PriceAlertsTable,
			Columns: []string{channel.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Channel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
