// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/product"
	"choseclothes/ent/source"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Listing is the model entity for the Listing schema.
type Listing struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// SellerName holds the value of the "seller_name" field.
	SellerName string `json:"seller_name,omitempty"`
	// SellerRating holds the value of the "seller_rating" field.
	SellerRating float64 `json:"seller_rating,omitempty"`
	// ProductURL holds the value of the "product_url" field.
	ProductURL string `json:"product_url,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ListingQuery when eager-loading is set.
	Edges            ListingEdges `json:"edges"`
	product_listings *int
	source_listings  *int
	selectValues     sql.SelectValues
}

// ListingEdges holds the relations/edges for other nodes in the graph.
type ListingEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// Source holds the value of the source edge.
	Source *Source `json:"source,omitempty"`
	// PriceAlerts holds the value of the price_alerts edge.
	PriceAlerts []*PriceAlert `json:"price_alerts,omitempty"`
	// PriceHistory holds the value of the price_history edge.
	PriceHistory []*PriceHistory `json:"price_history,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListingEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// SourceOrErr returns the Source value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ListingEdges) SourceOrErr() (*Source, error) {
	if e.Source != nil {
		return e.Source, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: source.Label}
	}
	return nil, &NotLoadedError{edge: "source"}
}

// PriceAlertsOrErr returns the PriceAlerts value or an error if the edge
// was not loaded in eager-loading.
func (e ListingEdges) PriceAlertsOrErr() ([]*PriceAlert, error) {
	if e.loadedTypes[2] {
		return e.PriceAlerts, nil
	}
	return nil, &NotLoadedError{edge: "price_alerts"}
}

// PriceHistoryOrErr returns the PriceHistory value or an error if the edge
// was not loaded in eager-loading.
func (e ListingEdges) PriceHistoryOrErr() ([]*PriceHistory, error) {
	if e.loadedTypes[3] {
		return e.PriceHistory, nil
	}
	return nil, &NotLoadedError{edge: "price_history"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Listing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case listing.FieldIsActive:
			values[i] = new(sql.NullBool)
		case listing.FieldSellerRating:
			values[i] = new(sql.NullFloat64)
		case listing.FieldID:
			values[i] = new(sql.NullInt64)
		case listing.FieldExternalID, listing.FieldTitle, listing.FieldSellerName, listing.FieldProductURL, listing.FieldCurrency:
			values[i] = new(sql.NullString)
		case listing.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case listing.ForeignKeys[0]: // product_listings
			values[i] = new(sql.NullInt64)
		case listing.ForeignKeys[1]: // source_listings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Listing fields.
func (_m *Listing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case listing.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case listing.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		case listing.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case listing.FieldSellerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field seller_name", values[i])
			} else if value.Valid {
				_m.SellerName = value.String
			}
		case listing.FieldSellerRating:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field seller_rating", values[i])
			} else if value.Valid {
				_m.SellerRating = value.Float64
			}
		case listing.FieldProductURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_url", values[i])
			} else if value.Valid {
				_m.ProductURL = value.String
			}
		case listing.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case listing.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case listing.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case listing.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field product_listings", value)
			} else if value.Valid {
				_m.product_listings = new(int)
				*_m.product_listings = int(value.Int64)
			}
		case listing.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field source_listings", value)
			} else if value.Valid {
				_m.source_listings = new(int)
				*_m.source_listings = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Listing.
// This includes values selected through modifiers, order, etc.
func (_m *Listing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the Listing entity.
func (_m *Listing) QueryProduct() *ProductQuery {
	return NewListingClient(_m.config).QueryProduct(_m)
}

// QuerySource queries the "source" edge of the Listing entity.
func (_m *Listing) QuerySource() *SourceQuery {
	return NewListingClient(_m.config).QuerySource(_m)
}

// QueryPriceAlerts queries the "price_alerts" edge of the Listing entity.
func (_m *Listing) QueryPriceAlerts() *PriceAlertQuery {
	return NewListingClient(_m.config).QueryPriceAlerts(_m)
}

// QueryPriceHistory queries the "price_history" edge of the Listing entity.
func (_m *Listing) QueryPriceHistory() *PriceHistoryQuery {
	return NewListingClient(_m.config).QueryPriceHistory(_m)
}

// Update returns a builder for updating this Listing.
// Note that you need to call Listing.Unwrap() before calling this method if this Listing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Listing) Update() *ListingUpdateOne {
	return NewListingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Listing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Listing) Unwrap() *Listing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Listing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Listing) String() string {
	var builder strings.Builder
	builder.WriteString("Listing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("seller_name=")
	builder.WriteString(_m.SellerName)
	builder.WriteString(", ")
	builder.WriteString("seller_rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.SellerRating))
	builder.WriteString(", ")
	builder.WriteString("product_url=")
	builder.WriteString(_m.ProductURL)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Listings is a parsable slice of Listing.
type Listings []*Listing
