// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/pricealert"
	"choseclothes/ent/pricehistory"
	"choseclothes/ent/product"
	"choseclothes/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// ListingCreate is the builder for creating a Listing entity.
type ListingCreate struct {
	config
	mutation *ListingMutation
	hooks    []Hook
}

// SetExternalID sets the "external_id" field.
func (_c *ListingCreate) SetExternalID(v string) *ListingCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ListingCreate) SetTitle(v string) *ListingCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetSellerName sets the "seller_name" field.
func (_c *ListingCreate) SetSellerName(v string) *ListingCreate {
	_c.mutation.SetSellerName(v)
	return _c
}

// SetNillableSellerName sets the "seller_name" field if the given value is not nil.
func (_c *ListingCreate) SetNillableSellerName(v *string) *ListingCreate {
	if v != nil {
		_c.SetSellerName(*v)
	}
	return _c
}

// SetSellerRating sets the "seller_rating" field.
func (_c *ListingCreate) SetSellerRating(v float64) *ListingCreate {
	_c.mutation.SetSellerRating(v)
	return _c
}

// SetNillableSellerRating sets the "seller_rating" field if the given value is not nil.
func (_c *ListingCreate) SetNillableSellerRating(v *float64) *ListingCreate {
	if v != nil {
		_c.SetSellerRating(*v)
	}
	return _c
}

// SetProductURL sets the "product_url" field.
func (_c *ListingCreate) SetProductURL(v string) *ListingCreate {
	_c.mutation.SetProductURL(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ListingCreate) SetCurrency(v string) *ListingCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ListingCreate) SetNillableCurrency(v *string) *ListingCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ListingCreate) SetIsActive(v bool) *ListingCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ListingCreate) SetNillableIsActive(v *bool) *ListingCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ListingCreate) SetCreatedAt(v time.Time) *ListingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ListingCreate) SetNillableCreatedAt(v *time.Time) *ListingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ListingCreate) SetID(v uuid.UUID) *ListingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ListingCreate) SetNillableID(v *uuid.UUID) *ListingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_c *ListingCreate) SetProductID(id uuid.UUID) *ListingCreate {
	_c.mutation.SetProductID(id)
	return _c
}

// SetProduct sets the "product" edge to the Product entity.
func (_c *ListingCreate) SetProduct(v *Product) *ListingCreate {
	return _c.SetProductID(v.ID)
}

// SetSourceID sets the "source" edge to the Source entity by ID.
func (_c *ListingCreate) SetSourceID(id int) *ListingCreate {
	_c.mutation.SetSourceID(id)
	return _c
}

// SetSource sets the "source" edge to the Source entity.
func (_c *ListingCreate) SetSource(v *Source) *ListingCreate {
	return _c.SetSourceID(v.ID)
}

// AddPriceAlertIDs adds the "price_alerts" edge to the PriceAlert entity by IDs.
func (_c *ListingCreate) AddPriceAlertIDs(ids ...int) *ListingCreate {
	_c.mutation.AddPriceAlertIDs(ids...)
	return _c
}

// AddPriceAlerts adds the "price_alerts" edges to the PriceAlert entity.
func (_c *ListingCreate) AddPriceAlerts(v ...*PriceAlert) *ListingCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPriceAlertIDs(ids...)
}

// AddPriceHistoryIDs adds the "price_history" edge to the PriceHistory entity by IDs.
func (_c *ListingCreate) AddPriceHistoryIDs(ids ...int) *ListingCreate {
	_c.mutation.AddPriceHistoryIDs(ids...)
	return _c
}

// AddPriceHistory adds the "price_history" edges to the PriceHistory entity.
func (_c *ListingCreate) AddPriceHistory(v ...*PriceHistory) *ListingCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPriceHistoryIDs(ids...)
}

// Mutation returns the ListingMutation object of the builder.
func (_c *ListingCreate) Mutation() *ListingMutation {
	return _c.mutation
}

// Save creates the Listing in the database.
func (_c *ListingCreate) Save(ctx context.Context) (*Listing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ListingCreate) SaveX(ctx context.Context) *Listing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ListingCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := listing.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := listing.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := listing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := listing.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ListingCreate) check() error {
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Listing.external_id"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := listing.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Listing.external_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Listing.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := listing.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Listing.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductURL(); !ok {
		return &ValidationError{Name: "product_url", err: errors.New(`ent: missing required field "Listing.product_url"`)}
	}
	if v, ok := _c.mutation.ProductURL(); ok {
		if err := listing.ProductURLValidator(v); err != nil {
			return &ValidationError{Name: "product_url", err: fmt.Errorf(`ent: validator failed for field "Listing.product_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Listing.currency"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Listing.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Listing.created_at"`)}
	}
	if len(_c.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "Listing.product"`)}
	}
	if len(_c.mutation.SourceIDs()) == 0 {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required edge "Listing.source"`)}
	}
	return nil
}

func (_c *ListingCreate) sqlSave(ctx context.Context) (*Listing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ListingCreate) createSpec() (*Listing, *sqlgraph.CreateSpec) {
	var (
		_node = &Listing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(listing.Table, sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(listing.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(listing.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.SellerName(); ok {
		_spec.SetField(listing.FieldSellerName, field.TypeString, value)
		_node.SellerName = value
	}
	if value, ok := _c.mutation.SellerRating(); ok {
		_spec.SetField(listing.FieldSellerRating, field.TypeFloat64, value)
		_node.SellerRating = value
	}
	if value, ok := _c.mutation.ProductURL(); ok {
		_spec.SetField(listing.FieldProductURL, field.TypeString, value)
		_node.ProductURL = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(listing.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(listing.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(listing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.ProductTable,
			Columns: []string{listing.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.product_listings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.SourceTable,
			Columns: []string{listing.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.source_listings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PriceAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PriceHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ListingCreateBulk is the builder for creating many Listing entities in bulk.
type ListingCreateBulk struct {
	config
	err      error
	builders []*ListingCreate
}

// Save creates the Listing entities in the database.
func (_c *ListingCreateBulk) Save(ctx context.Context) ([]*Listing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Listing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ListingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ListingCreateBulk) SaveX(ctx context.Context) []*Listing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ListingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ListingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
