// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricealert"
	"choseclothes/ent/pricehistory"
	"choseclothes/ent/product"
	"choseclothes/ent/source"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ListingUpdate is the builder for updating Listing entities.
type ListingUpdate struct {
	config
	hooks    []Hook
	mutation *ListingMutation
}

// Where appends a list predicates to the ListingUpdate builder.
func (_u *ListingUpdate) Where(ps ...predicate.Listing) *ListingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *ListingUpdate) SetExternalID(v string) *ListingUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableExternalID(v *string) *ListingUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ListingUpdate) SetTitle(v string) *ListingUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableTitle(v *string) *ListingUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSellerName sets the "seller_name" field.
func (_u *ListingUpdate) SetSellerName(v string) *ListingUpdate {
	_u.mutation.SetSellerName(v)
	return _u
}

// SetNillableSellerName sets the "seller_name" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableSellerName(v *string) *ListingUpdate {
	if v != nil {
		_u.SetSellerName(*v)
	}
	return _u
}

// ClearSellerName clears the value of the "seller_name" field.
func (_u *ListingUpdate) ClearSellerName() *ListingUpdate {
	_u.mutation.ClearSellerName()
	return _u
}

// SetSellerRating sets the "seller_rating" field.
func (_u *ListingUpdate) SetSellerRating(v float64) *ListingUpdate {
	_u.mutation.ResetSellerRating()
	_u.mutation.SetSellerRating(v)
	return _u
}

// SetNillableSellerRating sets the "seller_rating" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableSellerRating(v *float64) *ListingUpdate {
	if v != nil {
		_u.SetSellerRating(*v)
	}
	return _u
}

// AddSellerRating adds value to the "seller_rating" field.
func (_u *ListingUpdate) AddSellerRating(v float64) *ListingUpdate {
	_u.mutation.AddSellerRating(v)
	return _u
}

// ClearSellerRating clears the value of the "seller_rating" field.
func (_u *ListingUpdate) ClearSellerRating() *ListingUpdate {
	_u.mutation.ClearSellerRating()
	return _u
}

// SetProductURL sets the "product_url" field.
func (_u *ListingUpdate) SetProductURL(v string) *ListingUpdate {
	_u.mutation.SetProductURL(v)
	return _u
}

// SetNillableProductURL sets the "product_url" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableProductURL(v *string) *ListingUpdate {
	if v != nil {
		_u.SetProductURL(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ListingUpdate) SetCurrency(v string) *ListingUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableCurrency(v *string) *ListingUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ListingUpdate) SetIsActive(v bool) *ListingUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableIsActive(v *bool) *ListingUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ListingUpdate) SetCreatedAt(v time.Time) *ListingUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ListingUpdate) SetNillableCreatedAt(v *time.Time) *ListingUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_u *ListingUpdate) SetProductID(id int) *ListingUpdate {
	_u.mutation.SetProductID(id)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ListingUpdate) SetProduct(v *Product) *ListingUpdate {
	return _u.SetProductID(v.ID)
}

// SetSourceID sets the "source" edge to the Source entity by ID.
func (_u *ListingUpdate) SetSourceID(id int) *ListingUpdate {
	_u.mutation.SetSourceID(id)
	return _u
}

// SetSource sets the "source" edge to the Source entity.
func (_u *ListingUpdate) SetSource(v *Source) *ListingUpdate {
	return _u.SetSourceID(v.ID)
}

// AddPriceAlertIDs adds the "price_alerts" edge to the PriceAlert entity by IDs.
func (_u *ListingUpdate) AddPriceAlertIDs(ids ...int) *ListingUpdate {
	_u.mutation.AddPriceAlertIDs(ids...)
	return _u
}

// AddPriceAlerts adds the "price_alerts" edges to the PriceAlert entity.
func (_u *ListingUpdate) AddPriceAlerts(v ...*PriceAlert) *ListingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceAlertIDs(ids...)
}

// AddPriceHistoryIDs adds the "price_history" edge to the PriceHistory entity by IDs.
func (_u *ListingUpdate) AddPriceHistoryIDs(ids ...int) *ListingUpdate {
	_u.mutation.AddPriceHistoryIDs(ids...)
	return _u
}

// AddPriceHistory adds the "price_history" edges to the PriceHistory entity.
func (_u *ListingUpdate) AddPriceHistory(v ...*PriceHistory) *ListingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceHistoryIDs(ids...)
}

// Mutation returns the ListingMutation object of the builder.
func (_u *ListingUpdate) Mutation() *ListingMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ListingUpdate) ClearProduct() *ListingUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *ListingUpdate) ClearSource() *ListingUpdate {
	_u.mutation.ClearSource()
	return _u
}

// ClearPriceAlerts clears all "price_alerts" edges to the PriceAlert entity.
func (_u *ListingUpdate) ClearPriceAlerts() *ListingUpdate {
	_u.mutation.ClearPriceAlerts()
	return _u
}

// RemovePriceAlertIDs removes the "price_alerts" edge to PriceAlert entities by IDs.
func (_u *ListingUpdate) RemovePriceAlertIDs(ids ...int) *ListingUpdate {
	_u.mutation.RemovePriceAlertIDs(ids...)
	return _u
}

// RemovePriceAlerts removes "price_alerts" edges to PriceAlert entities.
func (_u *ListingUpdate) RemovePriceAlerts(v ...*PriceAlert) *ListingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceAlertIDs(ids...)
}

// ClearPriceHistory clears all "price_history" edges to the PriceHistory entity.
func (_u *ListingUpdate) ClearPriceHistory() *ListingUpdate {
	_u.mutation.ClearPriceHistory()
	return _u
}

// RemovePriceHistoryIDs removes the "price_history" edge to PriceHistory entities by IDs.
func (_u *ListingUpdate) RemovePriceHistoryIDs(ids ...int) *ListingUpdate {
	_u.mutation.RemovePriceHistoryIDs(ids...)
	return _u
}

// RemovePriceHistory removes "price_history" edges to PriceHistory entities.
func (_u *ListingUpdate) RemovePriceHistory(v ...*PriceHistory) *ListingUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ListingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ListingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListingUpdate) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := listing.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Listing.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := listing.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Listing.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductURL(); ok {
		if err := listing.ProductURLValidator(v); err != nil {
			return &ValidationError{Name: "product_url", err: fmt.Errorf(`ent: validator failed for field "Listing.product_url": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listing.product"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listing.source"`)
	}
	return nil
}

func (_u *ListingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listing.Table, listing.Columns, sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(listing.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(listing.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SellerName(); ok {
		_spec.SetField(listing.FieldSellerName, field.TypeString, value)
	}
	if _u.mutation.SellerNameCleared() {
		_spec.ClearField(listing.FieldSellerName, field.TypeString)
	}
	if value, ok := _u.mutation.SellerRating(); ok {
		_spec.SetField(listing.FieldSellerRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellerRating(); ok {
		_spec.AddField(listing.FieldSellerRating, field.TypeFloat64, value)
	}
	if _u.mutation.SellerRatingCleared() {
		_spec.ClearField(listing.FieldSellerRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductURL(); ok {
		_spec.SetField(listing.FieldProductURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(listing.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(listing.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(listing.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.ProductTable,
			Columns: []string{listing.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.ProductTable,
			Columns: []string{listing.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.SourceTable,
			Columns: []string{listing.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.SourceTable,
			Columns: []string{listing.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceAlertsIDs(); len(nodes) > 0 && !_u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PriceHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceHistoryIDs(); len(nodes) > 0 && !_u.mutation.PriceHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ListingUpdateOne is the builder for updating a single Listing entity.
type ListingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ListingMutation
}

// SetExternalID sets the "external_id" field.
func (_u *ListingUpdateOne) SetExternalID(v string) *ListingUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableExternalID(v *string) *ListingUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ListingUpdateOne) SetTitle(v string) *ListingUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableTitle(v *string) *ListingUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSellerName sets the "seller_name" field.
func (_u *ListingUpdateOne) SetSellerName(v string) *ListingUpdateOne {
	_u.mutation.SetSellerName(v)
	return _u
}

// SetNillableSellerName sets the "seller_name" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableSellerName(v *string) *ListingUpdateOne {
	if v != nil {
		_u.SetSellerName(*v)
	}
	return _u
}

// ClearSellerName clears the value of the "seller_name" field.
func (_u *ListingUpdateOne) ClearSellerName() *ListingUpdateOne {
	_u.mutation.ClearSellerName()
	return _u
}

// SetSellerRating sets the "seller_rating" field.
func (_u *ListingUpdateOne) SetSellerRating(v float64) *ListingUpdateOne {
	_u.mutation.ResetSellerRating()
	_u.mutation.SetSellerRating(v)
	return _u
}

// SetNillableSellerRating sets the "seller_rating" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableSellerRating(v *float64) *ListingUpdateOne {
	if v != nil {
		_u.SetSellerRating(*v)
	}
	return _u
}

// AddSellerRating adds value to the "seller_rating" field.
func (_u *ListingUpdateOne) AddSellerRating(v float64) *ListingUpdateOne {
	_u.mutation.AddSellerRating(v)
	return _u
}

// ClearSellerRating clears the value of the "seller_rating" field.
func (_u *ListingUpdateOne) ClearSellerRating() *ListingUpdateOne {
	_u.mutation.ClearSellerRating()
	return _u
}

// SetProductURL sets the "product_url" field.
func (_u *ListingUpdateOne) SetProductURL(v string) *ListingUpdateOne {
	_u.mutation.SetProductURL(v)
	return _u
}

// SetNillableProductURL sets the "product_url" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableProductURL(v *string) *ListingUpdateOne {
	if v != nil {
		_u.SetProductURL(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ListingUpdateOne) SetCurrency(v string) *ListingUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableCurrency(v *string) *ListingUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ListingUpdateOne) SetIsActive(v bool) *ListingUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableIsActive(v *bool) *ListingUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ListingUpdateOne) SetCreatedAt(v time.Time) *ListingUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ListingUpdateOne) SetNillableCreatedAt(v *time.Time) *ListingUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (_u *ListingUpdateOne) SetProductID(id int) *ListingUpdateOne {
	_u.mutation.SetProductID(id)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ListingUpdateOne) SetProduct(v *Product) *ListingUpdateOne {
	return _u.SetProductID(v.ID)
}

// SetSourceID sets the "source" edge to the Source entity by ID.
func (_u *ListingUpdateOne) SetSourceID(id int) *ListingUpdateOne {
	_u.mutation.SetSourceID(id)
	return _u
}

// SetSource sets the "source" edge to the Source entity.
func (_u *ListingUpdateOne) SetSource(v *Source) *ListingUpdateOne {
	return _u.SetSourceID(v.ID)
}

// AddPriceAlertIDs adds the "price_alerts" edge to the PriceAlert entity by IDs.
func (_u *ListingUpdateOne) AddPriceAlertIDs(ids ...int) *ListingUpdateOne {
	_u.mutation.AddPriceAlertIDs(ids...)
	return _u
}

// AddPriceAlerts adds the "price_alerts" edges to the PriceAlert entity.
func (_u *ListingUpdateOne) AddPriceAlerts(v ...*PriceAlert) *ListingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceAlertIDs(ids...)
}

// AddPriceHistoryIDs adds the "price_history" edge to the PriceHistory entity by IDs.
func (_u *ListingUpdateOne) AddPriceHistoryIDs(ids ...int) *ListingUpdateOne {
	_u.mutation.AddPriceHistoryIDs(ids...)
	return _u
}

// AddPriceHistory adds the "price_history" edges to the PriceHistory entity.
func (_u *ListingUpdateOne) AddPriceHistory(v ...*PriceHistory) *ListingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPriceHistoryIDs(ids...)
}

// Mutation returns the ListingMutation object of the builder.
func (_u *ListingUpdateOne) Mutation() *ListingMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ListingUpdateOne) ClearProduct() *ListingUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// ClearSource clears the "source" edge to the Source entity.
func (_u *ListingUpdateOne) ClearSource() *ListingUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// ClearPriceAlerts clears all "price_alerts" edges to the PriceAlert entity.
func (_u *ListingUpdateOne) ClearPriceAlerts() *ListingUpdateOne {
	_u.mutation.ClearPriceAlerts()
	return _u
}

// RemovePriceAlertIDs removes the "price_alerts" edge to PriceAlert entities by IDs.
func (_u *ListingUpdateOne) RemovePriceAlertIDs(ids ...int) *ListingUpdateOne {
	_u.mutation.RemovePriceAlertIDs(ids...)
	return _u
}

// RemovePriceAlerts removes "price_alerts" edges to PriceAlert entities.
func (_u *ListingUpdateOne) RemovePriceAlerts(v ...*PriceAlert) *ListingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceAlertIDs(ids...)
}

// ClearPriceHistory clears all "price_history" edges to the PriceHistory entity.
func (_u *ListingUpdateOne) ClearPriceHistory() *ListingUpdateOne {
	_u.mutation.ClearPriceHistory()
	return _u
}

// RemovePriceHistoryIDs removes the "price_history" edge to PriceHistory entities by IDs.
func (_u *ListingUpdateOne) RemovePriceHistoryIDs(ids ...int) *ListingUpdateOne {
	_u.mutation.RemovePriceHistoryIDs(ids...)
	return _u
}

// RemovePriceHistory removes "price_history" edges to PriceHistory entities.
func (_u *ListingUpdateOne) RemovePriceHistory(v ...*PriceHistory) *ListingUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePriceHistoryIDs(ids...)
}

// Where appends a list predicates to the ListingUpdate builder.
func (_u *ListingUpdateOne) Where(ps ...predicate.Listing) *ListingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ListingUpdateOne) Select(field string, fields ...string) *ListingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Listing entity.
func (_u *ListingUpdateOne) Save(ctx context.Context) (*Listing, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ListingUpdateOne) SaveX(ctx context.Context) *Listing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ListingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ListingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ListingUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := listing.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Listing.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := listing.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Listing.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductURL(); ok {
		if err := listing.ProductURLValidator(v); err != nil {
			return &ValidationError{Name: "product_url", err: fmt.Errorf(`ent: validator failed for field "Listing.product_url": %w`, err)}
		}
	}
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listing.product"`)
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Listing.source"`)
	}
	return nil
}

func (_u *ListingUpdateOne) sqlSave(ctx context.Context) (_node *Listing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(listing.Table, listing.Columns, sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Listing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, listing.FieldID)
		for _, f := range fields {
			if !listing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != listing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(listing.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(listing.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.SellerName(); ok {
		_spec.SetField(listing.FieldSellerName, field.TypeString, value)
	}
	if _u.mutation.SellerNameCleared() {
		_spec.ClearField(listing.FieldSellerName, field.TypeString)
	}
	if value, ok := _u.mutation.SellerRating(); ok {
		_spec.SetField(listing.FieldSellerRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSellerRating(); ok {
		_spec.AddField(listing.FieldSellerRating, field.TypeFloat64, value)
	}
	if _u.mutation.SellerRatingCleared() {
		_spec.ClearField(listing.FieldSellerRating, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ProductURL(); ok {
		_spec.SetField(listing.FieldProductURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(listing.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(listing.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(listing.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.ProductTable,
			Columns: []string{listing.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.ProductTable,
			Columns: []string{listing.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.SourceTable,
			Columns: []string{listing.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   listing.SourceTable,
			Columns: []string{listing.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceAlertsIDs(); len(nodes) > 0 && !_u.mutation.PriceAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceAlertsTable,
			Columns: []string{listing.PriceAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PriceHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPriceHistoryIDs(); len(nodes) > 0 && !_u.mutation.PriceHistoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PriceHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   listing.PriceHistoryTable,
			Columns: []string{listing.PriceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Listing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{listing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
