// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricehistory"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceHistoryDelete is the builder for deleting a PriceHistory entity.
type PriceHistoryDelete struct {
	config
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// Where appends a list predicates to the PriceHistoryDelete builder.
func (_d *PriceHistoryDelete) Where(ps ...predicate.PriceHistory) *PriceHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PriceHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PriceHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PriceHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pricehistory.Table, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PriceHistoryDeleteOne is the builder for deleting a single PriceHistory entity.
type PriceHistoryDeleteOne struct {
	_d *PriceHistoryDelete
}

// Where appends a list predicates to the PriceHistoryDelete builder.
func (_d *PriceHistoryDeleteOne) Where(ps ...predicate.PriceHistory) *PriceHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PriceHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pricehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PriceHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
