// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/listing"
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricealert"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// PriceAlertQuery is the builder for querying PriceAlert entities.
type PriceAlertQuery struct {
	config
	ctx         *QueryContext
	order       []pricealert.OrderOption
	inters      []Interceptor
	predicates  []predicate.PriceAlert
	withChannel *ChannelQuery
	withListing *ListingQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PriceAlertQuery builder.
func (_q *PriceAlertQuery) Where(ps ...predicate.PriceAlert) *PriceAlertQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PriceAlertQuery) Limit(limit int) *PriceAlertQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PriceAlertQuery) Offset(offset int) *PriceAlertQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PriceAlertQuery) Unique(unique bool) *PriceAlertQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PriceAlertQuery) Order(o ...pricealert.OrderOption) *PriceAlertQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChannel chains the current query on the "channel" edge.
func (_q *PriceAlertQuery) QueryChannel() *ChannelQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricealert.Table, pricealert.FieldID, selector),
			sqlgraph.To(channel.Table, channel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pricealert.ChannelTable, pricealert.ChannelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryListing chains the current query on the "listing" edge.
func (_q *PriceAlertQuery) QueryListing() *ListingQuery {
	query := (&ListingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricealert.Table, pricealert.FieldID, selector),
			sqlgraph.To(listing.Table, listing.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pricealert.ListingTable, pricealert.ListingColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PriceAlert entity from the query.
// Returns a *NotFoundError when no PriceAlert was found.
func (_q *PriceAlertQuery) First(ctx context.Context) (*PriceAlert, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pricealert.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PriceAlertQuery) FirstX(ctx context.Context) *PriceAlert {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PriceAlert ID from the query.
// Returns a *NotFoundError when no PriceAlert ID was found.
func (_q *PriceAlertQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pricealert.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PriceAlertQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PriceAlert entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PriceAlert entity is found.
// Returns a *NotFoundError when no PriceAlert entities are found.
func (_q *PriceAlertQuery) Only(ctx context.Context) (*PriceAlert, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pricealert.Label}
	default:
		return nil, &NotSingularError{pricealert.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PriceAlertQuery) OnlyX(ctx context.Context) *PriceAlert {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PriceAlert ID in the query.
// Returns a *NotSingularError when more than one PriceAlert ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PriceAlertQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pricealert.Label}
	default:
		err = &NotSingularError{pricealert.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PriceAlertQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PriceAlerts.
func (_q *PriceAlertQuery) All(ctx context.Context) ([]*PriceAlert, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PriceAlert, *PriceAlertQuery]()
	return withInterceptors[[]*PriceAlert](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PriceAlertQuery) AllX(ctx context.Context) []*PriceAlert {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PriceAlert IDs.
func (_q *PriceAlertQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pricealert.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PriceAlertQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PriceAlertQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PriceAlertQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PriceAlertQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PriceAlertQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PriceAlertQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PriceAlertQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PriceAlertQuery) Clone() *PriceAlertQuery {
	if _q == nil {
		return nil
	}
	return &PriceAlertQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]pricealert.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.PriceAlert{}, _q.predicates...),
		withChannel: _q.withChannel.Clone(),
		withListing: _q.withListing.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChannel tells the query-builder to eager-load the nodes that are connected to
// the "channel" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PriceAlertQuery) WithChannel(opts ...func(*ChannelQuery)) *PriceAlertQuery {
	query := (&ChannelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChannel = query
	return _q
}

// WithListing tells the query-builder to eager-load the nodes that are connected to
// the "listing" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PriceAlertQuery) WithListing(opts ...func(*ListingQuery)) *PriceAlertQuery {
	query := (&ListingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withListing = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TargetPrice float64 `json:"target_price,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PriceAlert.Query().
//		GroupBy(pricealert.FieldTargetPrice).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PriceAlertQuery) GroupBy(field string, fields ...string) *PriceAlertGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PriceAlertGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pricealert.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TargetPrice float64 `json:"target_price,omitempty"`
//	}
//
//	client.PriceAlert.Query().
//		Select(pricealert.FieldTargetPrice).
//		Scan(ctx, &v)
func (_q *PriceAlertQuery) Select(fields ...string) *PriceAlertSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PriceAlertSelect{PriceAlertQuery: _q}
	sbuild.label = pricealert.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PriceAlertSelect configured with the given aggregations.
func (_q *PriceAlertQuery) Aggregate(fns ...AggregateFunc) *PriceAlertSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PriceAlertQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pricealert.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PriceAlertQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PriceAlert, error) {
	var (
		nodes       = []*PriceAlert{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withChannel != nil,
			_q.withListing != nil,
		}
	)
	if _q.withChannel != nil || _q.withListing != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, pricealert.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PriceAlert).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PriceAlert{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChannel; query != nil {
		if err := _q.loadChannel(ctx, query, nodes, nil,
			func(n *PriceAlert, e *Channel) { n.Edges.Channel = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withListing; query != nil {
		if err := _q.loadListing(ctx, query, nodes, nil,
			func(n *PriceAlert, e *Listing) { n.Edges.Listing = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PriceAlertQuery) loadChannel(ctx context.Context, query *ChannelQuery, nodes []*PriceAlert, init func(*PriceAlert), assign func(*PriceAlert, *Channel)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PriceAlert)
	for i := range nodes {
		if nodes[i].channel_price_alerts == nil {
			continue
		}
		fk := *nodes[i].channel_price_alerts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(channel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "channel_price_alerts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PriceAlertQuery) loadListing(ctx context.Context, query *ListingQuery, nodes []*PriceAlert, init func(*PriceAlert), assign func(*PriceAlert, *Listing)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PriceAlert)
	for i := range nodes {
		if nodes[i].listing_price_alerts == nil {
			continue
		}
		fk := *nodes[i].listing_price_alerts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(listing.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "listing_price_alerts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PriceAlertQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PriceAlertQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pricealert.Table, pricealert.Columns, sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricealert.FieldID)
		for i := range fields {
			if fields[i] != pricealert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PriceAlertQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pricealert.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pricealert.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PriceAlertGroupBy is the group-by builder for PriceAlert entities.
type PriceAlertGroupBy struct {
	selector
	build *PriceAlertQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PriceAlertGroupBy) Aggregate(fns ...AggregateFunc) *PriceAlertGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PriceAlertGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PriceAlertQuery, *PriceAlertGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PriceAlertGroupBy) sqlScan(ctx context.Context, root *PriceAlertQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PriceAlertSelect is the builder for selecting fields of PriceAlert entities.
type PriceAlertSelect struct {
	*PriceAlertQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PriceAlertSelect) Aggregate(fns ...AggregateFunc) *PriceAlertSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PriceAlertSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PriceAlertQuery, *PriceAlertSelect](ctx, _s.PriceAlertQuery, _s, _s.inters, v)
}

func (_s *PriceAlertSelect) sqlScan(ctx context.Context, root *PriceAlertQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
