// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricehistory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// PriceHistoryUpdate is the builder for updating PriceHistory entities.
type PriceHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (_u *PriceHistoryUpdate) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PriceHistoryUpdate) SetPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PriceHistoryUpdate) SetNillablePrice(v *float64) *PriceHistoryUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PriceHistoryUpdate) AddPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetDiscountPrice sets the "discount_price" field.
func (_u *PriceHistoryUpdate) SetDiscountPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.ResetDiscountPrice()
	_u.mutation.SetDiscountPrice(v)
	return _u
}

// SetNillableDiscountPrice sets the "discount_price" field if the given value is not nil.
func (_u *PriceHistoryUpdate) SetNillableDiscountPrice(v *float64) *PriceHistoryUpdate {
	if v != nil {
		_u.SetDiscountPrice(*v)
	}
	return _u
}

// AddDiscountPrice adds value to the "discount_price" field.
func (_u *PriceHistoryUpdate) AddDiscountPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.AddDiscountPrice(v)
	return _u
}

// ClearDiscountPrice clears the value of the "discount_price" field.
func (_u *PriceHistoryUpdate) ClearDiscountPrice() *PriceHistoryUpdate {
	_u.mutation.ClearDiscountPrice()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *PriceHistoryUpdate) SetRecordedAt(v time.Time) *PriceHistoryUpdate {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *PriceHistoryUpdate) SetNillableRecordedAt(v *time.Time) *PriceHistoryUpdate {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_u *PriceHistoryUpdate) SetListingID(id uuid.UUID) *PriceHistoryUpdate {
	_u.mutation.SetListingID(id)
	return _u
}

// SetListing sets the "listing" edge to the Listing entity.
func (_u *PriceHistoryUpdate) SetListing(v *Listing) *PriceHistoryUpdate {
	return _u.SetListingID(v.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (_u *PriceHistoryUpdate) Mutation() *PriceHistoryMutation {
	return _u.mutation
}

// ClearListing clears the "listing" edge to the Listing entity.
func (_u *PriceHistoryUpdate) ClearListing() *PriceHistoryUpdate {
	_u.mutation.ClearListing()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceHistoryUpdate) check() error {
	if _u.mutation.ListingCleared() && len(_u.mutation.ListingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceHistory.listing"`)
	}
	return nil
}

func (_u *PriceHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountPrice(); ok {
		_spec.SetField(pricehistory.FieldDiscountPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountPrice(); ok {
		_spec.AddField(pricehistory.FieldDiscountPrice, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountPriceCleared() {
		_spec.ClearField(pricehistory.FieldDiscountPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(pricehistory.FieldRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.ListingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ListingTable,
			Columns: []string{pricehistory.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ListingTable,
			Columns: []string{pricehistory.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceHistoryUpdateOne is the builder for updating a single PriceHistory entity.
type PriceHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// SetPrice sets the "price" field.
func (_u *PriceHistoryUpdateOne) SetPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PriceHistoryUpdateOne) SetNillablePrice(v *float64) *PriceHistoryUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PriceHistoryUpdateOne) AddPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetDiscountPrice sets the "discount_price" field.
func (_u *PriceHistoryUpdateOne) SetDiscountPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.ResetDiscountPrice()
	_u.mutation.SetDiscountPrice(v)
	return _u
}

// SetNillableDiscountPrice sets the "discount_price" field if the given value is not nil.
func (_u *PriceHistoryUpdateOne) SetNillableDiscountPrice(v *float64) *PriceHistoryUpdateOne {
	if v != nil {
		_u.SetDiscountPrice(*v)
	}
	return _u
}

// AddDiscountPrice adds value to the "discount_price" field.
func (_u *PriceHistoryUpdateOne) AddDiscountPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.AddDiscountPrice(v)
	return _u
}

// ClearDiscountPrice clears the value of the "discount_price" field.
func (_u *PriceHistoryUpdateOne) ClearDiscountPrice() *PriceHistoryUpdateOne {
	_u.mutation.ClearDiscountPrice()
	return _u
}

// SetRecordedAt sets the "recorded_at" field.
func (_u *PriceHistoryUpdateOne) SetRecordedAt(v time.Time) *PriceHistoryUpdateOne {
	_u.mutation.SetRecordedAt(v)
	return _u
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_u *PriceHistoryUpdateOne) SetNillableRecordedAt(v *time.Time) *PriceHistoryUpdateOne {
	if v != nil {
		_u.SetRecordedAt(*v)
	}
	return _u
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_u *PriceHistoryUpdateOne) SetListingID(id uuid.UUID) *PriceHistoryUpdateOne {
	_u.mutation.SetListingID(id)
	return _u
}

// SetListing sets the "listing" edge to the Listing entity.
func (_u *PriceHistoryUpdateOne) SetListing(v *Listing) *PriceHistoryUpdateOne {
	return _u.SetListingID(v.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (_u *PriceHistoryUpdateOne) Mutation() *PriceHistoryMutation {
	return _u.mutation
}

// ClearListing clears the "listing" edge to the Listing entity.
func (_u *PriceHistoryUpdateOne) ClearListing() *PriceHistoryUpdateOne {
	_u.mutation.ClearListing()
	return _u
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (_u *PriceHistoryUpdateOne) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceHistoryUpdateOne) Select(field string, fields ...string) *PriceHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PriceHistory entity.
func (_u *PriceHistoryUpdateOne) Save(ctx context.Context) (*PriceHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceHistoryUpdateOne) SaveX(ctx context.Context) *PriceHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceHistoryUpdateOne) check() error {
	if _u.mutation.ListingCleared() && len(_u.mutation.ListingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceHistory.listing"`)
	}
	return nil
}

func (_u *PriceHistoryUpdateOne) sqlSave(ctx context.Context) (_node *PriceHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricehistory.FieldID)
		for _, f := range fields {
			if !pricehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountPrice(); ok {
		_spec.SetField(pricehistory.FieldDiscountPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountPrice(); ok {
		_spec.AddField(pricehistory.FieldDiscountPrice, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountPriceCleared() {
		_spec.ClearField(pricehistory.FieldDiscountPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.RecordedAt(); ok {
		_spec.SetField(pricehistory.FieldRecordedAt, field.TypeTime, value)
	}
	if _u.mutation.ListingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ListingTable,
			Columns: []string{pricehistory.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ListingTable,
			Columns: []string{pricehistory.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PriceHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
