// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/listing"
	"choseclothes/ent/pricealert"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// PriceAlertCreate is the builder for creating a PriceAlert entity.
type PriceAlertCreate struct {
	config
	mutation *PriceAlertMutation
	hooks    []Hook
}

// SetTargetPrice sets the "target_price" field.
func (_c *PriceAlertCreate) SetTargetPrice(v float64) *PriceAlertCreate {
	_c.mutation.SetTargetPrice(v)
	return _c
}

// SetNillableTargetPrice sets the "target_price" field if the given value is not nil.
func (_c *PriceAlertCreate) SetNillableTargetPrice(v *float64) *PriceAlertCreate {
	if v != nil {
		_c.SetTargetPrice(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *PriceAlertCreate) SetIsActive(v bool) *PriceAlertCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *PriceAlertCreate) SetNillableIsActive(v *bool) *PriceAlertCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_c *PriceAlertCreate) SetLastNotifiedAt(v time.Time) *PriceAlertCreate {
	_c.mutation.SetLastNotifiedAt(v)
	return _c
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_c *PriceAlertCreate) SetNillableLastNotifiedAt(v *time.Time) *PriceAlertCreate {
	if v != nil {
		_c.SetLastNotifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PriceAlertCreate) SetCreatedAt(v time.Time) *PriceAlertCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PriceAlertCreate) SetNillableCreatedAt(v *time.Time) *PriceAlertCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_c *PriceAlertCreate) SetChannelID(id uuid.UUID) *PriceAlertCreate {
	_c.mutation.SetChannelID(id)
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *PriceAlertCreate) SetChannel(v *Channel) *PriceAlertCreate {
	return _c.SetChannelID(v.ID)
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_c *PriceAlertCreate) SetListingID(id uuid.UUID) *PriceAlertCreate {
	_c.mutation.SetListingID(id)
	return _c
}

// SetListing sets the "listing" edge to the Listing entity.
func (_c *PriceAlertCreate) SetListing(v *Listing) *PriceAlertCreate {
	return _c.SetListingID(v.ID)
}

// Mutation returns the PriceAlertMutation object of the builder.
func (_c *PriceAlertCreate) Mutation() *PriceAlertMutation {
	return _c.mutation
}

// Save creates the PriceAlert in the database.
func (_c *PriceAlertCreate) Save(ctx context.Context) (*PriceAlert, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PriceAlertCreate) SaveX(ctx context.Context) *PriceAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceAlertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceAlertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PriceAlertCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := pricealert.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := pricealert.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PriceAlertCreate) check() error {
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "PriceAlert.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PriceAlert.created_at"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "PriceAlert.channel"`)}
	}
	if len(_c.mutation.ListingIDs()) == 0 {
		return &ValidationError{Name: "listing", err: errors.New(`ent: missing required edge "PriceAlert.listing"`)}
	}
	return nil
}

func (_c *PriceAlertCreate) sqlSave(ctx context.Context) (*PriceAlert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PriceAlertCreate) createSpec() (*PriceAlert, *sqlgraph.CreateSpec) {
	var (
		_node = &PriceAlert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricealert.Table, sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TargetPrice(); ok {
		_spec.SetField(pricealert.FieldTargetPrice, field.TypeFloat64, value)
		_node.TargetPrice = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(pricealert.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.LastNotifiedAt(); ok {
		_spec.SetField(pricealert.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricealert.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ChannelTable,
			Columns: []string{pricealert.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.channel_price_alerts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ListingTable,
			Columns: []string{pricealert.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.listing_price_alerts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PriceAlertCreateBulk is the builder for creating many PriceAlert entities in bulk.
type PriceAlertCreateBulk struct {
	config
	err      error
	builders []*PriceAlertCreate
}

// Save creates the PriceAlert entities in the database.
func (_c *PriceAlertCreateBulk) Save(ctx context.Context) ([]*PriceAlert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PriceAlert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PriceAlertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PriceAlertCreateBulk) SaveX(ctx context.Context) []*PriceAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceAlertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceAlertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
