// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/listing"
	"choseclothes/ent/predicate"
	"choseclothes/ent/pricealert"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceAlertUpdate is the builder for updating PriceAlert entities.
type PriceAlertUpdate struct {
	config
	hooks    []Hook
	mutation *PriceAlertMutation
}

// Where appends a list predicates to the PriceAlertUpdate builder.
func (_u *PriceAlertUpdate) Where(ps ...predicate.PriceAlert) *PriceAlertUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetPrice sets the "target_price" field.
func (_u *PriceAlertUpdate) SetTargetPrice(v float64) *PriceAlertUpdate {
	_u.mutation.ResetTargetPrice()
	_u.mutation.SetTargetPrice(v)
	return _u
}

// SetNillableTargetPrice sets the "target_price" field if the given value is not nil.
func (_u *PriceAlertUpdate) SetNillableTargetPrice(v *float64) *PriceAlertUpdate {
	if v != nil {
		_u.SetTargetPrice(*v)
	}
	return _u
}

// AddTargetPrice adds value to the "target_price" field.
func (_u *PriceAlertUpdate) AddTargetPrice(v float64) *PriceAlertUpdate {
	_u.mutation.AddTargetPrice(v)
	return _u
}

// ClearTargetPrice clears the value of the "target_price" field.
func (_u *PriceAlertUpdate) ClearTargetPrice() *PriceAlertUpdate {
	_u.mutation.ClearTargetPrice()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PriceAlertUpdate) SetIsActive(v bool) *PriceAlertUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PriceAlertUpdate) SetNillableIsActive(v *bool) *PriceAlertUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *PriceAlertUpdate) SetLastNotifiedAt(v time.Time) *PriceAlertUpdate {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *PriceAlertUpdate) SetNillableLastNotifiedAt(v *time.Time) *PriceAlertUpdate {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *PriceAlertUpdate) ClearLastNotifiedAt() *PriceAlertUpdate {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PriceAlertUpdate) SetCreatedAt(v time.Time) *PriceAlertUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PriceAlertUpdate) SetNillableCreatedAt(v *time.Time) *PriceAlertUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *PriceAlertUpdate) SetChannelID(id int) *PriceAlertUpdate {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *PriceAlertUpdate) SetChannel(v *Channel) *PriceAlertUpdate {
	return _u.SetChannelID(v.ID)
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_u *PriceAlertUpdate) SetListingID(id int) *PriceAlertUpdate {
	_u.mutation.SetListingID(id)
	return _u
}

// SetListing sets the "listing" edge to the Listing entity.
func (_u *PriceAlertUpdate) SetListing(v *Listing) *PriceAlertUpdate {
	return _u.SetListingID(v.ID)
}

// Mutation returns the PriceAlertMutation object of the builder.
func (_u *PriceAlertUpdate) Mutation() *PriceAlertMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *PriceAlertUpdate) ClearChannel() *PriceAlertUpdate {
	_u.mutation.ClearChannel()
	return _u
}

// ClearListing clears the "listing" edge to the Listing entity.
func (_u *PriceAlertUpdate) ClearListing() *PriceAlertUpdate {
	_u.mutation.ClearListing()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceAlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceAlertUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceAlertUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceAlertUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceAlertUpdate) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceAlert.channel"`)
	}
	if _u.mutation.ListingCleared() && len(_u.mutation.ListingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceAlert.listing"`)
	}
	return nil
}

func (_u *PriceAlertUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricealert.Table, pricealert.Columns, sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetPrice(); ok {
		_spec.SetField(pricealert.FieldTargetPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTargetPrice(); ok {
		_spec.AddField(pricealert.FieldTargetPrice, field.TypeFloat64, value)
	}
	if _u.mutation.TargetPriceCleared() {
		_spec.ClearField(pricealert.FieldTargetPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(pricealert.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(pricealert.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(pricealert.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pricealert.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ChannelTable,
			Columns: []string{pricealert.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ChannelTable,
			Columns: []string{pricealert.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ListingTable,
			Columns: []string{pricealert.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ListingTable,
			Columns: []string{pricealert.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricealert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceAlertUpdateOne is the builder for updating a single PriceAlert entity.
type PriceAlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceAlertMutation
}

// SetTargetPrice sets the "target_price" field.
func (_u *PriceAlertUpdateOne) SetTargetPrice(v float64) *PriceAlertUpdateOne {
	_u.mutation.ResetTargetPrice()
	_u.mutation.SetTargetPrice(v)
	return _u
}

// SetNillableTargetPrice sets the "target_price" field if the given value is not nil.
func (_u *PriceAlertUpdateOne) SetNillableTargetPrice(v *float64) *PriceAlertUpdateOne {
	if v != nil {
		_u.SetTargetPrice(*v)
	}
	return _u
}

// AddTargetPrice adds value to the "target_price" field.
func (_u *PriceAlertUpdateOne) AddTargetPrice(v float64) *PriceAlertUpdateOne {
	_u.mutation.AddTargetPrice(v)
	return _u
}

// ClearTargetPrice clears the value of the "target_price" field.
func (_u *PriceAlertUpdateOne) ClearTargetPrice() *PriceAlertUpdateOne {
	_u.mutation.ClearTargetPrice()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PriceAlertUpdateOne) SetIsActive(v bool) *PriceAlertUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PriceAlertUpdateOne) SetNillableIsActive(v *bool) *PriceAlertUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *PriceAlertUpdateOne) SetLastNotifiedAt(v time.Time) *PriceAlertUpdateOne {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *PriceAlertUpdateOne) SetNillableLastNotifiedAt(v *time.Time) *PriceAlertUpdateOne {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *PriceAlertUpdateOne) ClearLastNotifiedAt() *PriceAlertUpdateOne {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PriceAlertUpdateOne) SetCreatedAt(v time.Time) *PriceAlertUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PriceAlertUpdateOne) SetNillableCreatedAt(v *time.Time) *PriceAlertUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetChannelID sets the "channel" edge to the Channel entity by ID.
func (_u *PriceAlertUpdateOne) SetChannelID(id int) *PriceAlertUpdateOne {
	_u.mutation.SetChannelID(id)
	return _u
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_u *PriceAlertUpdateOne) SetChannel(v *Channel) *PriceAlertUpdateOne {
	return _u.SetChannelID(v.ID)
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_u *PriceAlertUpdateOne) SetListingID(id int) *PriceAlertUpdateOne {
	_u.mutation.SetListingID(id)
	return _u
}

// SetListing sets the "listing" edge to the Listing entity.
func (_u *PriceAlertUpdateOne) SetListing(v *Listing) *PriceAlertUpdateOne {
	return _u.SetListingID(v.ID)
}

// Mutation returns the PriceAlertMutation object of the builder.
func (_u *PriceAlertUpdateOne) Mutation() *PriceAlertMutation {
	return _u.mutation
}

// ClearChannel clears the "channel" edge to the Channel entity.
func (_u *PriceAlertUpdateOne) ClearChannel() *PriceAlertUpdateOne {
	_u.mutation.ClearChannel()
	return _u
}

// ClearListing clears the "listing" edge to the Listing entity.
func (_u *PriceAlertUpdateOne) ClearListing() *PriceAlertUpdateOne {
	_u.mutation.ClearListing()
	return _u
}

// Where appends a list predicates to the PriceAlertUpdate builder.
func (_u *PriceAlertUpdateOne) Where(ps ...predicate.PriceAlert) *PriceAlertUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceAlertUpdateOne) Select(field string, fields ...string) *PriceAlertUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PriceAlert entity.
func (_u *PriceAlertUpdateOne) Save(ctx context.Context) (*PriceAlert, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceAlertUpdateOne) SaveX(ctx context.Context) *PriceAlert {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceAlertUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceAlertUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PriceAlertUpdateOne) check() error {
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceAlert.channel"`)
	}
	if _u.mutation.ListingCleared() && len(_u.mutation.ListingIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceAlert.listing"`)
	}
	return nil
}

func (_u *PriceAlertUpdateOne) sqlSave(ctx context.Context) (_node *PriceAlert, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricealert.Table, pricealert.Columns, sqlgraph.NewFieldSpec(pricealert.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceAlert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricealert.FieldID)
		for _, f := range fields {
			if !pricealert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricealert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetPrice(); ok {
		_spec.SetField(pricealert.FieldTargetPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTargetPrice(); ok {
		_spec.AddField(pricealert.FieldTargetPrice, field.TypeFloat64, value)
	}
	if _u.mutation.TargetPriceCleared() {
		_spec.ClearField(pricealert.FieldTargetPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(pricealert.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(pricealert.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(pricealert.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pricealert.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChannelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ChannelTable,
			Columns: []string{pricealert.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ChannelTable,
			Columns: []string{pricealert.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ListingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ListingTable,
			Columns: []string{pricealert.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricealert.ListingTable,
			Columns: []string{pricealert.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PriceAlert{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricealert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
