// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/listing"
	"choseclothes/ent/pricealert"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PriceAlert is the model entity for the PriceAlert schema.
type PriceAlert struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TargetPrice holds the value of the "target_price" field.
	TargetPrice float64 `json:"target_price,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// LastNotifiedAt holds the value of the "last_notified_at" field.
	LastNotifiedAt *time.Time `json:"last_notified_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceAlertQuery when eager-loading is set.
	Edges                PriceAlertEdges `json:"edges"`
	channel_price_alerts *int
	listing_price_alerts *int
	selectValues         sql.SelectValues
}

// PriceAlertEdges holds the relations/edges for other nodes in the graph.
type PriceAlertEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// Listing holds the value of the listing edge.
	Listing *Listing `json:"listing,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceAlertEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// ListingOrErr returns the Listing value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceAlertEdges) ListingOrErr() (*Listing, error) {
	if e.Listing != nil {
		return e.Listing, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: listing.Label}
	}
	return nil, &NotLoadedError{edge: "listing"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PriceAlert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricealert.FieldIsActive:
			values[i] = new(sql.NullBool)
		case pricealert.FieldTargetPrice:
			values[i] = new(sql.NullFloat64)
		case pricealert.FieldID:
			values[i] = new(sql.NullInt64)
		case pricealert.FieldLastNotifiedAt, pricealert.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pricealert.ForeignKeys[0]: // channel_price_alerts
			values[i] = new(sql.NullInt64)
		case pricealert.ForeignKeys[1]: // listing_price_alerts
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PriceAlert fields.
func (_m *PriceAlert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricealert.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pricealert.FieldTargetPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field target_price", values[i])
			} else if value.Valid {
				_m.TargetPrice = value.Float64
			}
		case pricealert.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case pricealert.FieldLastNotifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_notified_at", values[i])
			} else if value.Valid {
				_m.LastNotifiedAt = new(time.Time)
				*_m.LastNotifiedAt = value.Time
			}
		case pricealert.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pricealert.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field channel_price_alerts", value)
			} else if value.Valid {
				_m.channel_price_alerts = new(int)
				*_m.channel_price_alerts = int(value.Int64)
			}
		case pricealert.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field listing_price_alerts", value)
			} else if value.Valid {
				_m.listing_price_alerts = new(int)
				*_m.listing_price_alerts = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PriceAlert.
// This includes values selected through modifiers, order, etc.
func (_m *PriceAlert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the PriceAlert entity.
func (_m *PriceAlert) QueryChannel() *ChannelQuery {
	return NewPriceAlertClient(_m.config).QueryChannel(_m)
}

// QueryListing queries the "listing" edge of the PriceAlert entity.
func (_m *PriceAlert) QueryListing() *ListingQuery {
	return NewPriceAlertClient(_m.config).QueryListing(_m)
}

// Update returns a builder for updating this PriceAlert.
// Note that you need to call PriceAlert.Unwrap() before calling this method if this PriceAlert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PriceAlert) Update() *PriceAlertUpdateOne {
	return NewPriceAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PriceAlert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PriceAlert) Unwrap() *PriceAlert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PriceAlert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PriceAlert) String() string {
	var builder strings.Builder
	builder.WriteString("PriceAlert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetPrice))
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.LastNotifiedAt; v != nil {
		builder.WriteString("last_notified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PriceAlerts is a parsable slice of PriceAlert.
type PriceAlerts []*PriceAlert
