// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/pricehistory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceHistoryCreate is the builder for creating a PriceHistory entity.
type PriceHistoryCreate struct {
	config
	mutation *PriceHistoryMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (_c *PriceHistoryCreate) SetPrice(v float64) *PriceHistoryCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetDiscountPrice sets the "discount_price" field.
func (_c *PriceHistoryCreate) SetDiscountPrice(v float64) *PriceHistoryCreate {
	_c.mutation.SetDiscountPrice(v)
	return _c
}

// SetNillableDiscountPrice sets the "discount_price" field if the given value is not nil.
func (_c *PriceHistoryCreate) SetNillableDiscountPrice(v *float64) *PriceHistoryCreate {
	if v != nil {
		_c.SetDiscountPrice(*v)
	}
	return _c
}

// SetRecordedAt sets the "recorded_at" field.
func (_c *PriceHistoryCreate) SetRecordedAt(v time.Time) *PriceHistoryCreate {
	_c.mutation.SetRecordedAt(v)
	return _c
}

// SetNillableRecordedAt sets the "recorded_at" field if the given value is not nil.
func (_c *PriceHistoryCreate) SetNillableRecordedAt(v *time.Time) *PriceHistoryCreate {
	if v != nil {
		_c.SetRecordedAt(*v)
	}
	return _c
}

// SetListingID sets the "listing" edge to the Listing entity by ID.
func (_c *PriceHistoryCreate) SetListingID(id int) *PriceHistoryCreate {
	_c.mutation.SetListingID(id)
	return _c
}

// SetListing sets the "listing" edge to the Listing entity.
func (_c *PriceHistoryCreate) SetListing(v *Listing) *PriceHistoryCreate {
	return _c.SetListingID(v.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (_c *PriceHistoryCreate) Mutation() *PriceHistoryMutation {
	return _c.mutation
}

// Save creates the PriceHistory in the database.
func (_c *PriceHistoryCreate) Save(ctx context.Context) (*PriceHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PriceHistoryCreate) SaveX(ctx context.Context) *PriceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PriceHistoryCreate) defaults() {
	if _, ok := _c.mutation.RecordedAt(); !ok {
		v := pricehistory.DefaultRecordedAt()
		_c.mutation.SetRecordedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PriceHistoryCreate) check() error {
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "PriceHistory.price"`)}
	}
	if _, ok := _c.mutation.RecordedAt(); !ok {
		return &ValidationError{Name: "recorded_at", err: errors.New(`ent: missing required field "PriceHistory.recorded_at"`)}
	}
	if len(_c.mutation.ListingIDs()) == 0 {
		return &ValidationError{Name: "listing", err: errors.New(`ent: missing required edge "PriceHistory.listing"`)}
	}
	return nil
}

func (_c *PriceHistoryCreate) sqlSave(ctx context.Context) (*PriceHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PriceHistoryCreate) createSpec() (*PriceHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &PriceHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricehistory.Table, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(pricehistory.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.DiscountPrice(); ok {
		_spec.SetField(pricehistory.FieldDiscountPrice, field.TypeFloat64, value)
		_node.DiscountPrice = value
	}
	if value, ok := _c.mutation.RecordedAt(); ok {
		_spec.SetField(pricehistory.FieldRecordedAt, field.TypeTime, value)
		_node.RecordedAt = value
	}
	if nodes := _c.mutation.ListingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ListingTable,
			Columns: []string{pricehistory.ListingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.listing_price_history = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PriceHistoryCreateBulk is the builder for creating many PriceHistory entities in bulk.
type PriceHistoryCreateBulk struct {
	config
	err      error
	builders []*PriceHistoryCreate
}

// Save creates the PriceHistory entities in the database.
func (_c *PriceHistoryCreateBulk) Save(ctx context.Context) ([]*PriceHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PriceHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PriceHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PriceHistoryCreateBulk) SaveX(ctx context.Context) []*PriceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PriceHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PriceHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
