// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/pricehistory"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PriceHistory is the model entity for the PriceHistory schema.
type PriceHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// DiscountPrice holds the value of the "discount_price" field.
	DiscountPrice float64 `json:"discount_price,omitempty"`
	// RecordedAt holds the value of the "recorded_at" field.
	RecordedAt time.Time `json:"recorded_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceHistoryQuery when eager-loading is set.
	Edges                 PriceHistoryEdges `json:"edges"`
	listing_price_history *int
	selectValues          sql.SelectValues
}

// PriceHistoryEdges holds the relations/edges for other nodes in the graph.
type PriceHistoryEdges struct {
	// Listing holds the value of the listing edge.
	Listing *Listing `json:"listing,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ListingOrErr returns the Listing value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceHistoryEdges) ListingOrErr() (*Listing, error) {
	if e.Listing != nil {
		return e.Listing, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: listing.Label}
	}
	return nil, &NotLoadedError{edge: "listing"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PriceHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricehistory.FieldPrice, pricehistory.FieldDiscountPrice:
			values[i] = new(sql.NullFloat64)
		case pricehistory.FieldID:
			values[i] = new(sql.NullInt64)
		case pricehistory.FieldRecordedAt:
			values[i] = new(sql.NullTime)
		case pricehistory.ForeignKeys[0]: // listing_price_history
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PriceHistory fields.
func (_m *PriceHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pricehistory.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case pricehistory.FieldDiscountPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_price", values[i])
			} else if value.Valid {
				_m.DiscountPrice = value.Float64
			}
		case pricehistory.FieldRecordedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field recorded_at", values[i])
			} else if value.Valid {
				_m.RecordedAt = value.Time
			}
		case pricehistory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field listing_price_history", value)
			} else if value.Valid {
				_m.listing_price_history = new(int)
				*_m.listing_price_history = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PriceHistory.
// This includes values selected through modifiers, order, etc.
func (_m *PriceHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryListing queries the "listing" edge of the PriceHistory entity.
func (_m *PriceHistory) QueryListing() *ListingQuery {
	return NewPriceHistoryClient(_m.config).QueryListing(_m)
}

// Update returns a builder for updating this PriceHistory.
// Note that you need to call PriceHistory.Unwrap() before calling this method if this PriceHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PriceHistory) Update() *PriceHistoryUpdateOne {
	return NewPriceHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PriceHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PriceHistory) Unwrap() *PriceHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PriceHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PriceHistory) String() string {
	var builder strings.Builder
	builder.WriteString("PriceHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("discount_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountPrice))
	builder.WriteString(", ")
	builder.WriteString("recorded_at=")
	builder.WriteString(_m.RecordedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PriceHistories is a parsable slice of PriceHistory.
type PriceHistories []*PriceHistory
