// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/channel"
	"choseclothes/ent/listing"
	"choseclothes/ent/pricealert"
	"choseclothes/ent/pricehistory"
	"choseclothes/ent/product"
	"choseclothes/ent/schema"
	"choseclothes/ent/source"
	"choseclothes/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescType is the schema descriptor for type field.
	channelDescType := channelFields[0].Descriptor()
	// channel.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	channel.TypeValidator = channelDescType.Validators[0].(func(string) error)
	// channelDescExternalID is the schema descriptor for external_id field.
	channelDescExternalID := channelFields[1].Descriptor()
	// channel.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	channel.ExternalIDValidator = channelDescExternalID.Validators[0].(func(string) error)
	// channelDescIsActive is the schema descriptor for is_active field.
	channelDescIsActive := channelFields[3].Descriptor()
	// channel.DefaultIsActive holds the default value on creation for the is_active field.
	channel.DefaultIsActive = channelDescIsActive.Default.(bool)
	// channelDescCreatedAt is the schema descriptor for created_at field.
	channelDescCreatedAt := channelFields[4].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the created_at field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	listingFields := schema.Listing{}.Fields()
	_ = listingFields
	// listingDescExternalID is the schema descriptor for external_id field.
	listingDescExternalID := listingFields[0].Descriptor()
	// listing.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	listing.ExternalIDValidator = listingDescExternalID.Validators[0].(func(string) error)
	// listingDescTitle is the schema descriptor for title field.
	listingDescTitle := listingFields[1].Descriptor()
	// listing.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	listing.TitleValidator = listingDescTitle.Validators[0].(func(string) error)
	// listingDescProductURL is the schema descriptor for product_url field.
	listingDescProductURL := listingFields[4].Descriptor()
	// listing.ProductURLValidator is a validator for the "product_url" field. It is called by the builders before save.
	listing.ProductURLValidator = listingDescProductURL.Validators[0].(func(string) error)
	// listingDescCurrency is the schema descriptor for currency field.
	listingDescCurrency := listingFields[5].Descriptor()
	// listing.DefaultCurrency holds the default value on creation for the currency field.
	listing.DefaultCurrency = listingDescCurrency.Default.(string)
	// listingDescIsActive is the schema descriptor for is_active field.
	listingDescIsActive := listingFields[6].Descriptor()
	// listing.DefaultIsActive holds the default value on creation for the is_active field.
	listing.DefaultIsActive = listingDescIsActive.Default.(bool)
	// listingDescCreatedAt is the schema descriptor for created_at field.
	listingDescCreatedAt := listingFields[7].Descriptor()
	// listing.DefaultCreatedAt holds the default value on creation for the created_at field.
	listing.DefaultCreatedAt = listingDescCreatedAt.Default.(func() time.Time)
	pricealertFields := schema.PriceAlert{}.Fields()
	_ = pricealertFields
	// pricealertDescIsActive is the schema descriptor for is_active field.
	pricealertDescIsActive := pricealertFields[1].Descriptor()
	// pricealert.DefaultIsActive holds the default value on creation for the is_active field.
	pricealert.DefaultIsActive = pricealertDescIsActive.Default.(bool)
	// pricealertDescCreatedAt is the schema descriptor for created_at field.
	pricealertDescCreatedAt := pricealertFields[3].Descriptor()
	// pricealert.DefaultCreatedAt holds the default value on creation for the created_at field.
	pricealert.DefaultCreatedAt = pricealertDescCreatedAt.Default.(func() time.Time)
	pricehistoryFields := schema.PriceHistory{}.Fields()
	_ = pricehistoryFields
	// pricehistoryDescRecordedAt is the schema descriptor for recorded_at field.
	pricehistoryDescRecordedAt := pricehistoryFields[2].Descriptor()
	// pricehistory.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	pricehistory.DefaultRecordedAt = pricehistoryDescRecordedAt.Default.(func() time.Time)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescTitle is the schema descriptor for title field.
	productDescTitle := productFields[0].Descriptor()
	// product.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	product.TitleValidator = productDescTitle.Validators[0].(func(string) error)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[4].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescName is the schema descriptor for name field.
	sourceDescName := sourceFields[0].Descriptor()
	// source.NameValidator is a validator for the "name" field. It is called by the builders before save.
	source.NameValidator = sourceDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescIsSubscriber is the schema descriptor for is_subscriber field.
	userDescIsSubscriber := userFields[5].Descriptor()
	// user.DefaultIsSubscriber holds the default value on creation for the is_subscriber field.
	user.DefaultIsSubscriber = userDescIsSubscriber.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
