// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/listing"
	"choseclothes/ent/predicate"
	"choseclothes/ent/source"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	uuid "github.com/gofrs/uuid/v5"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SourceUpdate) SetName(v string) *SourceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableName(v *string) *SourceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddListingIDs adds the "listings" edge to the Listing entity by IDs.
func (_u *SourceUpdate) AddListingIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.AddListingIDs(ids...)
	return _u
}

// AddListings adds the "listings" edges to the Listing entity.
func (_u *SourceUpdate) AddListings(v ...*Listing) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListingIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdate) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearListings clears all "listings" edges to the Listing entity.
func (_u *SourceUpdate) ClearListings() *SourceUpdate {
	_u.mutation.ClearListings()
	return _u
}

// RemoveListingIDs removes the "listings" edge to Listing entities by IDs.
func (_u *SourceUpdate) RemoveListingIDs(ids ...uuid.UUID) *SourceUpdate {
	_u.mutation.RemoveListingIDs(ids...)
	return _u
}

// RemoveListings removes "listings" edges to Listing entities.
func (_u *SourceUpdate) RemoveListings(v ...*Listing) *SourceUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := source.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Source.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
	}
	if _u.mutation.ListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListingsIDs(); len(nodes) > 0 && !_u.mutation.ListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetName sets the "name" field.
func (_u *SourceUpdateOne) SetName(v string) *SourceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableName(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddListingIDs adds the "listings" edge to the Listing entity by IDs.
func (_u *SourceUpdateOne) AddListingIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.AddListingIDs(ids...)
	return _u
}

// AddListings adds the "listings" edges to the Listing entity.
func (_u *SourceUpdateOne) AddListings(v ...*Listing) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddListingIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdateOne) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearListings clears all "listings" edges to the Listing entity.
func (_u *SourceUpdateOne) ClearListings() *SourceUpdateOne {
	_u.mutation.ClearListings()
	return _u
}

// RemoveListingIDs removes the "listings" edge to Listing entities by IDs.
func (_u *SourceUpdateOne) RemoveListingIDs(ids ...uuid.UUID) *SourceUpdateOne {
	_u.mutation.RemoveListingIDs(ids...)
	return _u
}

// RemoveListings removes "listings" edges to Listing entities.
func (_u *SourceUpdateOne) RemoveListings(v ...*Listing) *SourceUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveListingIDs(ids...)
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Source entity.
func (_u *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := source.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Source.name": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(source.FieldName, field.TypeString, value)
	}
	if _u.mutation.ListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedListingsIDs(); len(nodes) > 0 && !_u.mutation.ListingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ListingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ListingsTable,
			Columns: []string{source.ListingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(listing.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Source{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
