// Code generated by ent, DO NOT EDIT.

package ent

import (
	"choseclothes/ent/source"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Source is the model entity for the Source schema.
type Source struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SourceQuery when eager-loading is set.
	Edges        SourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SourceEdges holds the relations/edges for other nodes in the graph.
type SourceEdges struct {
	// Listings holds the value of the listings edge.
	Listings []*Listing `json:"listings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ListingsOrErr returns the Listings value or an error if the edge
// was not loaded in eager-loading.
func (e SourceEdges) ListingsOrErr() ([]*Listing, error) {
	if e.loadedTypes[0] {
		return e.Listings, nil
	}
	return nil, &NotLoadedError{edge: "listings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Source) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case source.FieldID:
			values[i] = new(sql.NullInt64)
		case source.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Source fields.
func (_m *Source) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case source.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case source.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Source.
// This includes values selected through modifiers, order, etc.
func (_m *Source) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryListings queries the "listings" edge of the Source entity.
func (_m *Source) QueryListings() *ListingQuery {
	return NewSourceClient(_m.config).QueryListings(_m)
}

// Update returns a builder for updating this Source.
// Note that you need to call Source.Unwrap() before calling this method if this Source
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Source) Update() *SourceUpdateOne {
	return NewSourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Source entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Source) Unwrap() *Source {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Source is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Source) String() string {
	var builder strings.Builder
	builder.WriteString("Source(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Sources is a parsable slice of Source.
type Sources []*Source
