// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Listing is the predicate function for listing builders.
type Listing func(*sql.Selector)

// PriceAlert is the predicate function for pricealert builders.
type PriceAlert func(*sql.Selector)

// PriceHistory is the predicate function for pricehistory builders.
type PriceHistory func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
